### ISSUE TITLE
Reserved word is not replaced correctly

### ISSUE THREAD

**Issue by TinkerWorX** [bridgedotnet/Bridge#1026]
I get the following exception when I compile the attached project. I've been unable to narrow down what causes the issue, but removing `ExpressionParser.cs`, `Token,cs` and `Operator.cs` removes the issue, so it is likely connected to those files/classes.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Error: Object reference not set to an instance of an object.    at Microsoft.Ajax.Utilities.JSParser.ParseFunction(FunctionType functionType, Context fncCtx)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionList(JSToken terminator)
   at Microsoft.Ajax.Utilities.JSParser.ParseMemberExpression(AstNode expression, List`1 newContexts)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpression(AstNode leftHandSide, Boolean single, Boolean bCanAssign, JSToken inToken)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseBlock()
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseIfStatement()
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseBlock()
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseWhileStatement()
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseFunctionBody(Block body)
   at Microsoft.Ajax.Utilities.JSParser.ParseFunction(FunctionType functionType, Context fncCtx)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseObjectLiteralProperty(Boolean isBindingPattern)
   at Microsoft.Ajax.Utilities.JSParser.ParseObjectLiteral(Boolean isBindingPattern)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionList(JSToken terminator)
   at Microsoft.Ajax.Utilities.JSParser.ParseMemberExpression(AstNode expression, List`1 newContexts)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseStatements(Block block)
   at Microsoft.Ajax.Utilities.JSParser.InternalParse()
   at Microsoft.Ajax.Utilities.JSParser.Parse(DocumentContext sourceContext)
   at Microsoft.Ajax.Utilities.Minifier.MinifyJavaScript(String source, CodeSettings codeSettings)
   at Bridge.Translator.Translator.SaveTo(String path, String defaultFileName)
   at Bridge.Build.GenerateScript.Execute()	ThreeOneSevenBee.Framework			

```
[TinkerWorX.BridgetNetErrorProject.zip](https://github.com/bridgedotnet/Bridge/files/156701/TinkerWorX.BridgetNetErrorProject.zip)

**UPDATE** by @DaniilVeriga:

A similar issue was also reported in this forum thread:
http://forums.bridge.net/forum/bridge-net-pro/bugs/1800

**Comment by vladsch** [comment]
Thanks for your test case. I found that problem is related with the following code in the `ExpressionParser.InFixToPostFix`

```
string function;
                if (IsFunction(inFix, ref i, out function))
                {
                    lastToken = Token.Function(function);
                    operators.Push(lastToken);
                    continue;
                }
```

The workaround - rename function to function1.
Bridge should rename reserved javascript words automatically. We will investigate why exactly that case is not resolved automatically

**Comment by TinkerWorX** [comment]
Thank you. The workaround worked and the project is now compiling.

**Comment by DaniilVeriga** [comment]
Here is a related bug report:
http://forums.bridge.net/forum/bridge-net-pro/bugs/1800
