### ISSUE TITLE
Commandline: Bridge.Builder -p flag is not working

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#1125]
If you try to build the working project in issue #1028 changing the exec command (**frontend.csproj:26**) from:
`build\Bridge.Builder.exe -lib $(OutputPath)$(AssemblyName).dll`
to:
`build\Bridge.Builder.exe -p frontend.csproj`

The build will fail with "object reference not set to an instance of object":
```
Bridge.Builder.Console : error 2016-03-30T11: 48:54:847 Error: exception level: 0 - Object reference not set to an instance of an object. [A:\devel\Object.NET\Bridge.NET\projects\issue1028\work\frontend.csproj]
  Stack trace:
     at Bridge.Translator.Translator.<>c__DisplayClass1d.<GetOutputPath>b__1b(XElement n)
     at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
     at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
     at Bridge.Translator.Translator.GetOutputPath(XDocument doc, String configuration)
     at Bridge.Translator.Translator.BuildAssemblyLocation(XDocument doc)
     at Bridge.Translator.Translator.ReadProjectFile()
     at Bridge.Translator.Translator.Translate()
     at Bridge.Builder.Program.Main(String[] args)
```
The error also happens if using:
`build\Bridge.Builder.exe -p frontend.csproj -lib $(OutputPath)$(AssemblyName).dll`

**Comment by fabriciomurta** [comment]
This sample project file pretty much describes the different test cases that should be supported:
1. the project uses a configuration (`Debug`, `Release`) in which no specific `OutputPath` is defined
   should use `buildr\` output path
2. the project uses a configuration that references a specific outputPath
   should use `build\` output path, for example, if it is `Debug`.

These two test cases are tested and works with the .csproj XML code in the shape below.
```XML
    <PropertyGroup>
        <AssemblyName>frontend</AssemblyName>
        <OutputPath>buildr\</OutputPath>
        <NoStdLib>true</NoStdLib>
        <WarningLevel>0</WarningLevel>
        <ScriptsPath>..\backend\www\js\</ScriptsPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>build\</OutputPath>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debuge' ">
        <OutputPath>builde\</OutputPath>
    </PropertyGroup>
```

Something not tested, is when the propertyGroup with the output path is written after the conditional ones:
```
    <PropertyGroup>
        <AssemblyName>frontend</AssemblyName>
        <NoStdLib>true</NoStdLib>
        <WarningLevel>0</WarningLevel>
        <ScriptsPath>..\backend\www\js\</ScriptsPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>build\</OutputPath>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debuge' ">
        <OutputPath>builde\</OutputPath>
    </PropertyGroup>
    <PropertyGroup>
        <OutputPath>buildr\</OutputPath>
    </PropertyGroup>
```

1. must check what does Visual Studio assumes when making the file output
2. must then compare visual studio's decision with Bridge's

**Comment by geoffreymcgill** [comment]
We need to determine if this is still an issue. Marking for review before the Bridge 16.0 release.
