### ISSUE TITLE
Compilation error with async Task<long> method.

### ISSUE THREAD

**Issue by Blackhex** [bridgedotnet/Bridge#1189]
I'm experiencing the following compilation error when a class has async Task<long> or async Task<Int64> method with Bridge 1.12.0, async Task<int> or async Task<Int32> works fine:

```
Error: Object reference not set to an instance of an object.    at Bridge.Translator.UnaryOperatorBlock.HandleDecimal(ResolveResult resolveOperator, Boolean isLong)
   at Bridge.Translator.UnaryOperatorBlock.VisitUnaryOperatorExpression()
   at Bridge.Translator.UnaryOperatorBlock.EmitConversionExpression()
   at Bridge.Translator.ConversionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitUnaryOperatorExpression(UnaryOperatorExpression unaryOperatorExpression)
   at ICSharpCode.NRefactory.CSharp.UnaryOperatorExpression.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.ExpressionListBlock.EmitExpressionList(IEnumerable`1 expressions, Expression paramArg)
   at Bridge.Translator.ExpressionListBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.AssignmentBlock.HandleType(ResolveResult resolveOperator, String variable, String op_name, KnownTypeCode typeCode)
   at Bridge.Translator.AssignmentBlock.HandleLong(ResolveResult resolveOperator, String variable, Boolean isUnsigned)
   at Bridge.Translator.AssignmentBlock.VisitAssignmentExpression()
   at Bridge.Translator.AssignmentBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitAssignmentExpression(AssignmentExpression assignmentExpression)
   at ICSharpCode.NRefactory.CSharp.AssignmentExpression.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.ExpressionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitExpressionStatement(ExpressionStatement expressionStatement)
   at ICSharpCode.NRefactory.CSharp.ExpressionStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.Block.<DoEmitBlock>b__64_0(AstNode child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Bridge.Translator.Block.DoEmitBlock()
   at Bridge.Translator.Block.EmitBlock()
   at Bridge.Translator.Block.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.IfElseBlock.VisitIfElseStatement()
   at Bridge.Translator.IfElseBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitIfElseStatement(IfElseStatement ifElseStatement)
   at ICSharpCode.NRefactory.CSharp.IfElseStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.Block.<DoEmitBlock>b__64_0(AstNode child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Bridge.Translator.Block.DoEmitBlock()
   at Bridge.Translator.Block.EmitBlock()
   at Bridge.Translator.Block.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.IfElseBlock.VisitIfElseStatement()
   at Bridge.Translator.IfElseBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitIfElseStatement(IfElseStatement ifElseStatement)
   at ICSharpCode.NRefactory.CSharp.IfElseStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.Block.<DoEmitBlock>b__64_0(AstNode child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Bridge.Translator.Block.DoEmitBlock()
   at Bridge.Translator.Block.EmitBlock()
   at Bridge.Translator.Block.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.AsyncBlock.EmitAsyncBody()
   at Bridge.Translator.AsyncBlock.EmitAsyncBlock()
   at Bridge.Translator.AsyncBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.VisitorMethodBlock.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.VisitorMethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.MethodBlock.EmitMethodsGroup(List`1 group)
   at Bridge.Translator.MethodBlock.EmitMethods(Dictionary`2 methods, Dictionary`2 properties, Dictionary`2 operators)
   at Bridge.Translator.MethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.ClassBlock.EmitInstantiableBlock()
   at Bridge.Translator.ClassBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.GenerateScript.Execute()
```

**Comment by vladsch** [comment]
Please post test sample which reproduces the issue

**Comment by Blackhex** [comment]
```
using Bridge.Html5;

using System.Threading.Tasks;

namespace AbakuGame {

    public class App {

        [Ready]
        public static async void Main() {
            var app = new App();
            var result = await app.Foo();
        }

        public async Task<long> Foo() {
            return -1;
        }
    }
}
```

**Comment by LeonidVeriga** [comment]
Hi @Blackhex,

Thanks for the test case. I created a sample in Libe Bridge http://live.bridge.net/#a5e178e64b239504bfd20a003dae6bcc
