### ISSUE TITLE
Support installing Bridge using NuGet to new Visual Studio C# Console Projects

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1330]
Current message during compilation if Bridge is added to a C# Console Project. 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Error: Project type (Exe) is not supported, please use Library instead of Exe    at Bridge.Translator.Translator.ReadProjectFile()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.GenerateScript.Execute()	ConsoleApplication1
```

<img width="804" alt="screenshot 2016-05-09 22 24 16" src="https://cloud.githubusercontent.com/assets/62210/15135563/e6ee6682-1634-11e6-9698-939d40ffe224.png">

It appears the NuGet installation happens properly. Error is thrown during compilation.

**Comment by LeonidVeriga** [comment]
@geoffreymcgill, this is due fix for #904
