### ISSUE TITLE
Strange error message in Bridge Live

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1450]
### Expected

Compile fine.

### Actual
```
C# to JavaScript Compilation Failed

System.NullReferenceException: Object reference not set to an instance of an object.
   at Bridge.Translator.Plugins.GetPluginPath(ITranslator translator, IAssemblyInfo config)
   at Bridge.Translator.Plugins.GetPlugins(ITranslator translator, IAssemblyInfo config, ILogger logger)
   at Bridge.Translator.Translator.Translate()
   at Live.LiveTranslator.Translate(String& output)
   at Live.TranslateHandler.Translate(String csCode)
```
### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#25d3cab39ef4fde4e490a823ed6681ab)
```csharp
public class App
{
    [Ready]
    public static void Main()
    {
        // Place code required to reproduce here
    }
}
```

**Comment by LeonidVeriga** [comment]
Hi @michaelcheers, thank you for reporting.
Fixed.
