### ISSUE TITLE
Methods support for ObjectLiteral

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1529]
### Expected

Compile fine.

### Actual

```
C# to JavaScript Compilation Failed

Bridge.Translator.TranslatorException: ObjectLiteral doesn't support methods: Demo.App/O
   at Bridge.Translator.Validator.CheckMethods(TypeDefinition type, ITranslator translator)
   at Bridge.Translator.Validator.CheckType(TypeDefinition type, ITranslator translator)
   at Bridge.Translator.Translator.AddNestedTypes(IEnumerable`1 types)
   at Bridge.Translator.Translator.AddNestedTypes(IEnumerable`1 types)
   at Bridge.Translator.Translator.ReadTypes(AssemblyDefinition assembly)
   at Bridge.Translator.Translator.InspectReferences()
   at Bridge.Translator.Translator.Translate()
   at Live.LiveTranslator.Translate(String& output)
   at Live.TranslateHandler.Translate(String csCode)
```

### Steps To Reproduce

[Live Bridge](http://live.bridge.net/#a65c4388a47554a41a5b03a0d44ccfd2)

```csharp
/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    [ObjectLiteral]
    class O
    {
        public int A;
        
        [Template("{this}.a")]
        public extern int GetA ();
    }
    
    public static void Main()
    {
    }
}
```

**Comment by michaelcheers** [comment]
This is also useful with interfaces: http://live.bridge.net/#9e4e666ecc619bdbe7e9f2b998150b15.

**Comment by geoffreymcgill** [comment]
We are working on this functionality and will add the ability to include all type Members in the `[ObjectLiteral]`, including Methods and Properties with proper getter/setter.

**Comment by LeonidVeriga** [comment]
Reminder: during development, check combination `[External]` + `[ObjectLiteral]` for #647 (check test case also).

**Comment by LeonidVeriga** [comment]
Releated bug #1819.
Fix notes https://github.com/bridgedotnet/Bridge/pull/1824#issue-176764255
