### ISSUE TITLE
ObjectLiteral fields must be FieldProperty if implementing an interface with FieldProperty

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1530]
### Expected

Compile fine.
### Actual

C# to JavaScript Compilation Failed

```
Bridge.Contract.EmitterException: The property [Property Demo.App+A.Name] is not marked as FieldProperty but implemented interface member has such attribute
   at Bridge.Translator.Inspector.VisitPropertyDeclaration(PropertyDeclaration propertyDeclaration)
   at ICSharpCode.NRefactory.CSharp.PropertyDeclaration.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Contract.Helpers.AcceptChildren(AstNode node, IAstVisitor visitor)
   at Bridge.Translator.Inspector.VisitTypeDeclaration(TypeDeclaration typeDeclaration)
   at Bridge.Translator.Inspector.VisitTypeDeclaration(TypeDeclaration typeDeclaration)
   at ICSharpCode.NRefactory.CSharp.TypeDeclaration.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Contract.Helpers.AcceptChildren(AstNode node, IAstVisitor visitor)
   at Bridge.Translator.Inspector.VisitNamespaceDeclaration(NamespaceDeclaration namespaceDeclaration)
   at ICSharpCode.NRefactory.CSharp.NamespaceDeclaration.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Contract.Helpers.AcceptChildren(AstNode node, IAstVisitor visitor)
   at Bridge.Translator.Inspector.VisitSyntaxTree(SyntaxTree node)
   at Bridge.Translator.Translator.InspectTypes(MemberResolver resolver, IAssemblyInfo config)
   at Bridge.Translator.Translator.Translate()
   at Live.LiveTranslator.Translate(String& output)
   at Live.TranslateHandler.Translate(String csCode)
```
### Steps To Reproduce

http://deck.net/70e38264f152cda6cffc52b810a9ab48

``` csharp
public class App
{
    [ObjectLiteral]
    class Child : Parent
    {
        // The [FieldProperty] Attribute is required, but
        // shouldn't be required because all 
        // properties are treated as Fields
        [FieldProperty]
        public string Name { get; set; }
    }

    interface Parent
    {
        [FieldProperty]
        string Name { get; set; }
    }
}
```

**Comment by gibbed** [comment]
Should you not be adding the FieldProperty attribute to your class as well? [Live Bridge](http://live.bridge.net/#f8c8de17b4578d134008f8ee7ef467aa)

**Comment by michaelcheers** [comment]
@gibbed, It's an [ObjectLiteral] and ObjectLiteral (s) by default have all FieldProperty (s). [Live Bridge](http://live.bridge.net/#3265abd559d0d078f3591a88b17716cf). Notice:
```javascript
System.Console.log(({ b: 7 }).b);
```
not .getB().

**Comment by gibbed** [comment]
@michaelcheers Ah, that makes sense now. Thanks.

**Comment by michaelcheers** [comment]
Is this ever going to be fixed?
