### ISSUE TITLE
Exception during translation

### ISSUE THREAD

**Issue by AndreyZM** [bridgedotnet/Bridge#1709]
When trying to compile big project got this Exception:

```c#
Error: Node is already used in another tree.
Parameter name: child    at ICSharpCode.NRefactory.CSharp.AstNode.AddChild[T](T child, Role`1 role)
   at ICSharpCode.NRefactory.CSharp.AstNodeCollection`1.Add(T element)
   at ICSharpCode.NRefactory.CSharp.AstNodeCollection`1.ReplaceWith(IEnumerable`1 nodes)
   at Bridge.Translator.PreconverterFixer.VisitInvocationExpression(InvocationExpression invocationExpression)
   at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitVariableInitializer(VariableInitializer variableInitializer)
   at ICSharpCode.NRefactory.CSharp.VariableInitializer.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitVariableDeclarationStatement(VariableDeclarationStatement variableDeclarationStatement)
   at ICSharpCode.NRefactory.CSharp.VariableDeclarationStatement.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at ICSharpCode.NRefactory.CSharp.MethodDeclaration.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitTypeDeclaration(TypeDeclaration typeDeclaration)
   at ICSharpCode.NRefactory.CSharp.TypeDeclaration.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitNamespaceDeclaration(NamespaceDeclaration namespaceDeclaration)
   at ICSharpCode.NRefactory.CSharp.NamespaceDeclaration.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.PreconverterFixer.VisitChildren(AstNode node)
   at ICSharpCode.NRefactory.CSharp.DepthFirstAstVisitor`1.VisitSyntaxTree(SyntaxTree unit)
   at ICSharpCode.NRefactory.CSharp.SyntaxTree.AcceptVisitor[T](IAstVisitor`1 visitor)
   at Bridge.Translator.Translator.Preconvert(MemberResolver resolver)
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.GenerateScript.Execute()
```

**Comment by vladsch** [comment]
We will appreciate if you can narrow a problem and post test sample. Or if you provide public link to download the project then we will try to find the issue

**Comment by geoffreymcgill** [comment]
What version of Bridge are you using?

A link to a [Live Bridge](http://live.bridge.net) sample the demonstrates how to reproduce the issue would be very helpful.

**Comment by AndreyZM** [comment]
Case detected

**Comment by LeonidVeriga** [comment]
Hi @AndreyZM. Thank you for the test case!
Here is a bit simplified sample ([Bridge Live](http://live.bridge.net/#e7b47da8cb16fc6a3c5bf8af09566ea4)):
```cs
public class App
{
    public void EventCallback(object callback)
    {
        // Removing either null or callback from the call fixes the problem
        var arguments = MakeArguments(null, callback);
    }

    public int MakeArguments<T>(params T[] args)
    {
        return args.Length;
    }
}
```

**Comment by vladsch** [comment]
Quick workaround:
```
var arguments = @makeArguments<object>(type, callback == null ? nullArg : callback, @params == null ? nullArg : @params);
```
