### ISSUE TITLE
bridge.builder.exe is not resolving GACed references

### ISSUE THREAD

**Issue by rufio620** [bridgedotnet/Bridge#2208]
### Expected
Bridge should resolve GACed assemblies.

### Actual

```
2016-12-29T05:19:15:670         Error           Error: exception level: 0 - Could not find file 'C:\Temp\BdDump\TestModule.dllBridgeModuleGen'.
Stack trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Bridge.Translator.Translator.LoadAssembly(String location, List`1 references)
   at Bridge.Translator.Translator.InspectReferences()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Builder.Program.Main(String[] args)
```

### Steps To Reproduce

Execute bridge.builder.exe -lib ..\TestModule.dll

Dll Exists in folder with all non GACed dependencies and source files

**Comment by geoffreymcgill** [comment]
Hi @rufio620 Thanks for the report. We will investigate.

**Comment by fabriciomurta** [comment]
Yes, System.* namespace is exported by Bridge.dll, if you just add the System.dll file and reference it, you'd get circular references.

**Comment by smx-smx** [comment]
If i remove System.dll it will error out tho
```
Could not find file '<path>\bin\Debug\System.dll'.    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Bridge.Translator.Translator.LoadAssembly(String location, List`1 references)
   at Bridge.Translator.Translator.LoadAssembly(String location, List`1 references)
   at Bridge.Translator.Translator.LoadAssembly(String location, List`1 references)
   at Bridge.Translator.Translator.LoadAssembly(String location, List`1 references)
   at Bridge.Translator.Translator.LoadAssembly(String location, List`1 references)
   at Bridge.Translator.Translator.InspectReferences()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.BridgeCompilerTask.Execute()
```

**Comment by fabriciomurta** [comment]
Maybe the project is referencing assemblies that are not bridge-aware? That would not work at all, if you create a project and referenced System.Xml.dll, just because the assembly has no instructions to be transpiled, and is likely referencing the System.dll assembly, which is not Bridge's.

**Comment by smx-smx** [comment]
Yes they are the real assemblies, the non bridge aware ones.
The idea was using reflection to extract the names of the methods (or type info in general), not to call methods directly.
If it's not an expected or possible scenario, good to know 😄 Thanks for the prompt reply anyways

But i'm wondering if reverting this on a local clone would work: https://github.com/bridgedotnet/Bridge/pull/2412. I actually modified it already but i don't know how to make Visual Studio use my Bridge.dll when building

**Comment by fabriciomurta** [comment]
This is rather turning into a discussion :)
We could move this to Bridge Forums if you don't mind creating an account there.

Well, but if you build bridge in Release mode, it should dump NuGet packages, just ensure you install these (in this case for `Bridge.Min` NuGet package) and you should be good.

If not sure NuGet is caching the package, you can either:
- move ahead the package version (to some prerelease to avoid conflicts with official releases)
- just unpack the Bridge.Min to your project's `packages/` folder
- copy over the Bridge.Translator DLL within the packages folder's Bridge.Min NuGet package

Well, among other possible choices...

**Comment by smx-smx** [comment]
I wrote onto Gitter as a start. If the idea turns out to be feasible I'll open a separate issue to track it (maybe could do it anyways)
