### ISSUE TITLE
Aspect sample doesnt work. on Deck

### ISSUE THREAD

**Issue by samuelGrahame** [bridgedotnet/Bridge#2260]
http://deck.net/aspect this does not work

C# to JavaScript Compilation Failed

```
System.MissingMethodException: Method not found: 'System.String Bridge.Contract.BridgeTypes.ToJsName(ICSharpCode.NRefactory.TypeSystem.IType, Bridge.Contract.IEmitter, Boolean, Boolean, Boolean, Boolean)'.
   at Bridge.Aspect.Plugin.ParameterAspectBlock.FindInheritedAspect(IType baseType, IMethod aspectMethod, List`1 aspectInfos, Int32 index)
   at Bridge.Aspect.Plugin.ParameterAspectBlock.GetAspects()
   at Bridge.Aspect.Plugin.AspectPlugin.GetAspects(IConstructorBlock constructorBlock)
   at Bridge.Aspect.Plugin.AspectPlugin.GetConstructorInjectors(IConstructorBlock constructorBlock)
   at Bridge.Translator.Plugins.GetConstructorInjectors(IConstructorBlock constructorBlock)
   at Bridge.Translator.ConstructorBlock.GetInjectors()
   at Bridge.Translator.ConstructorBlock.EmitInitMembers()
   at Bridge.Translator.ConstructorBlock.EmitCtorForInstantiableClass()
   at Bridge.Translator.ConstructorBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.ClassBlock.EmitInstantiableBlock()
   at Bridge.Translator.ClassBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
```

**Comment by geoffreymcgill** [comment]
Thanks for the report. We will get this fixed right away.

**Comment by geoffreymcgill** [comment]
This Exception has been fixed. The **Bridge.Aspect** assembly was out of date.

**Comment by samuelGrahame** [comment]
Good Work guys :)
