### ISSUE TITLE
Compilation fails if Anonymous type with bool field is used with ! unary operator

### ISSUE THREAD

**Issue by shadow-cs** [bridgedotnet/Bridge#2352]
Usage of anonymous type with bool field and `!` unary operator results in compilation failure.

Might be related to #2048.

### Steps To Reproduce

http://deck.net/367806ba2ea411aee6db5e4d43bf7f63/top

```c#
public class Program
{
    public static void Main()
    {
        var anonymous = new {IsTrue = false};
        bool b = !anonymous.IsTrue; // Doesn't work
        //bool b = anonymous.IsTrue == false; // Works
    }
}
```

### Expected Result

Should compile ok

### Actual Result

```
C# to JavaScript Compilation Failed

System.NullReferenceException: Object reference not set to an instance of an object.
   at Bridge.Translator.Validator.IsExternalType(ITypeDefinition typeDefinition, Boolean ignoreLiteral)
   at Bridge.Translator.UnaryOperatorBlock.VisitUnaryOperatorExpression()
   at Bridge.Translator.UnaryOperatorBlock.EmitConversionExpression()
   at Bridge.Translator.ConversionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitUnaryOperatorExpression(UnaryOperatorExpression unaryOperatorExpression)
   at ICSharpCode.NRefactory.CSharp.UnaryOperatorExpression.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.VariableBlock.VisitVariableDeclarationStatement()
   at Bridge.Translator.VariableBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitVariableDeclarationStatement(VariableDeclarationStatement variableDeclarationStatement)
   at ICSharpCode.NRefactory.CSharp.VariableDeclarationStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.Block.<>c__DisplayClass64_0.<DoEmitBlock>b__0(AstNode child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Bridge.Translator.Block.DoEmitBlock()
   at Bridge.Translator.Block.EmitBlock()
   at Bridge.Translator.Block.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.VisitorMethodBlock.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.VisitorMethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.MethodBlock.EmitMethods(Dictionary`2 methods, Dictionary`2 properties, Dictionary`2 operators)
   at Bridge.Translator.MethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.ClassBlock.EmitInstantiableBlock()
   at Bridge.Translator.ClassBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
```

**Comment by LeonidVeriga** [comment]
@shadow-cs, Thanks for informing us of this defect.
We will investigate and fix this defect.
