### ISSUE TITLE
Exception when a type already exists in a referenced DLL

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2410]
Steps to reproduce:
1. Create two Bridge.NET projects in the same solution
2. Create the same class in both of them
3. Reference Project A from Project B
4. Try to Build.
5. Observe this:

```
Error: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Bridge.Translator.Translator.AddNestedTypes(IEnumerable`1 types)
   at Bridge.Translator.Translator.ReadTypes(AssemblyDefinition assembly)
   at Bridge.Translator.Translator.InspectReferences()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.GenerateScript.Execute()
```

**Comment by vladsch** [comment]
At this moment, Bridge doesn't support two classes with same full name (namespace+name) in different assemblies. It is related with that fact that each class is shared in global javascript context (instead of sharing inside assembly only)

Bridge need to share classes inside assembly object to fix the issue but in this case class full name will contain assembly name in javascript

`var c = new TestLibrary1.Namespace.MyClass();`

We will discuss this issue but at this moment try to use unique main namespace in a project

**Comment by TriEdgeAI** [comment]
It's okay. We actually had a bug that we fixed thanks to this, but I just thought it would be nice to let you know there is an exception like that. :) We don't really need same name classes in two assemblies. Good luck!

**Comment by vladsch** [comment]
Atleast we have to provide meaningful exception message

**Comment by michaelcheers** [comment]
# See also
* #2796.
