### ISSUE TITLE
Compiler crash (Cannot find type: Anonymous Type) when reflection is enabled

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2605]
I can't repro this on Deck, but I'm not sure how a compiler crash would manifest itself there. I have some code with anonymous types:

```cs
[Test]
public void Passing_AnonymousTypes() => Assert.DeepEqual(new { A = "a", B = "b" }, new { A = "a", B = "b" });
```

When I enabled reflection for this assembly in `bridge.json` the compiler now crashes:

```text
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error : Error: Cannot find type: Anonymous Type    at Bridge.Contract.BridgeTypes.Get(IType type, Boolean safe)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.Emitter.GetTypeDefinition(IType type)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.MetadataUtils.GetCommonTypeProperties(IType type, IEmitter emitter)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.MetadataUtils.ConstructITypeMetadata(IType type, IEmitter emitter)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AnonymousTypeCreateBlock.GenereateMetadata(IAnonymousTypeConfig config)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AnonymousTypeCreateBlock.CreateAnonymousType(AnonymousType type)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AnonymousTypeCreateBlock.VisitAnonymousTypeCreateExpression()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AnonymousTypeCreateBlock.DoEmit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.Emitter.VisitAnonymousTypeCreateExpression(AnonymousTypeCreateExpression anonymousTypeCreateExpression)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at ICSharpCode.NRefactory.CSharp.AnonymousTypeCreateExpression.AcceptVisitor(IAstVisitor visitor)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.ExpressionListBlock.EmitExpressionList(IEnumerable`1 expressions, Expression paramArg)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.ExpressionListBlock.DoEmit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.InvocationBlock.VisitInvocationExpression()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.InvocationBlock.EmitConversionExpression()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.ConversionBlock.DoEmit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.Emitter.VisitInvocationExpression(InvocationExpression invocationExpression)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor(IAstVisitor visitor)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.ExpressionBlock.DoEmit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.Emitter.VisitExpressionStatement(ExpressionStatement expressionStatement)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at ICSharpCode.NRefactory.CSharp.ExpressionStatement.AcceptVisitor(IAstVisitor visitor)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.Block.<>c__DisplayClass64_0.<DoEmitBlock>b__0(AstNode child)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at System.Collections.Generic.List`1.ForEach(Action`1 action)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.Block.DoEmitBlock()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.Block.EmitBlock()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.Block.DoEmit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.VisitorMethodBlock.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.VisitorMethodBlock.DoEmit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.Emitter.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.MethodBlock.EmitMethodsGroup(List`1 group)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.MethodBlock.EmitMethods(Dictionary`2 methods, Dictionary`2 properties, Dictionary`2 operators)
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.MethodBlock.DoEmit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.ClassBlock.EmitInstantiableBlock()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.ClassBlock.DoEmit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.EmitBlock.DoEmit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.Emitter.Emit()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Translator.Translator.Translate()
1>C:\Hercules.Test\Hercules.Test.Tests\BasicTests.cs(179,60,179,84): error :    at Bridge.Build.GenerateScript.Execute()
2>------ Build started: Project: Hercules.Test.VsixForTesting, Configuration: DebugWithVsix Any CPU ------
```

I don't have any expectations about the anonymous types working with reflection (though I guess copying what C# does makes sense) though I guess it shouldn't crash like this.

**Comment by vladsch** [comment]
It is reproducible in Deck (v15.x)
https://deck.net/0dc656631af8439092cfa919d937dddc

But all fine in dev.deck (v16)
https://dev.deck.net/0dc656631af8439092cfa919d937dddc

So, it is fixed already

**Comment by DanTup** [comment]
Great; thanks! I keep forgetting to test on dev, sorry :(

Handy to know I can just change the hostname to load the same shared code too!
