### ISSUE TITLE
Invalid locales in bridge.json crash the compiler (Sequence contains no matching element)

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2607]
We incorrectly put `no-NB` for Norwegian instead of `nb-NO` and this happened during compilation:

```text
1>C:\Hercules.Test\packages\Bridge.Min.15.7.0\build\Bridge.Min.targets(18,5): error : Error: Sequence contains no matching element    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
1>C:\Hercules.Test\packages\Bridge.Min.15.7.0\build\Bridge.Min.targets(18,5): error :    at Bridge.Translator.Translator.ExtractLocales(String outputPath, Boolean nodebug)
1>C:\Hercules.Test\packages\Bridge.Min.15.7.0\build\Bridge.Min.targets(18,5): error :    at Bridge.Translator.Translator.ExtractCore(String outputPath, String projectPath, Boolean nodebug)
1>C:\Hercules.Test\packages\Bridge.Min.15.7.0\build\Bridge.Min.targets(18,5): error :    at Bridge.Translator.TranslatorProcessor.PostProcess()
1>C:\Hercules.Test\packages\Bridge.Min.15.7.0\build\Bridge.Min.targets(18,5): error :    at Bridge.Build.GenerateScript.Execute()
```

It would be better to provide a helpful message for invalid locales instead :-)

**Comment by geoffreymcgill** [comment]
Hi @DanTup – Thanks for the report. We will investigate.
