### ISSUE TITLE
Enabling Reflection creates compilation when using anonymous types.

### ISSUE THREAD

**Issue by rufio620** [bridgedotnet/Bridge#2621]
If the "reflection": { "enabled": true } setting is enabled in the Bridge.json file, anonymous types generate build errors.

### Steps To Reproduce
See attached [ReflectionLambdaIssue.zip](https://github.com/bridgedotnet/Bridge/files/962552/ReflectionLambdaIssue.zip)
Open solution in Visual Studio
 and attempt to build.
Build fails when "reflection" setting is enabled. 

### Expected Result

Build should succeed.

### Actual Result

Build fails with the following error
Severity	Code	Description	Project	File	Line	Suppression State
Error		Error: Cannot find type: Anonymous Type    at Bridge.Contract.BridgeTypes.Get(IType type, Boolean safe)
   at Bridge.Translator.Emitter.GetTypeDefinition(IType type)
   at Bridge.Translator.MetadataUtils.GetCommonTypeProperties(IType type, IEmitter emitter)
   at Bridge.Translator.MetadataUtils.ConstructITypeMetadata(IType type, IEmitter emitter)
   at Bridge.Translator.AnonymousTypeCreateBlock.GenereateMetadata(IAnonymousTypeConfig config)
   at Bridge.Translator.AnonymousTypeCreateBlock.CreateAnonymousType(AnonymousType type)
   at Bridge.Translator.AnonymousTypeCreateBlock.VisitAnonymousTypeCreateExpression()
   at Bridge.Translator.AnonymousTypeCreateBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitAnonymousTypeCreateExpression(AnonymousTypeCreateExpression anonymousTypeCreateExpression)
   at ICSharpCode.NRefactory.CSharp.AnonymousTypeCreateExpression.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.VariableBlock.VisitVariableDeclarationStatement()
   at Bridge.Translator.VariableBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitVariableDeclarationStatement(VariableDeclarationStatement variableDeclarationStatement)
   at ICSharpCode.NRefactory.CSharp.VariableDeclarationStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.Block.<>c__DisplayClass64_0.<DoEmitBlock>b__0(AstNode child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Bridge.Translator.Block.DoEmitBlock()
   at Bridge.Translator.Block.EmitBlock()
   at Bridge.Translator.Block.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.VisitorMethodBlock.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.VisitorMethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.MethodBlock.EmitMethods(Dictionary`2 methods, Dictionary`2 properties, Dictionary`2 operators)
   at Bridge.Translator.MethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.ClassBlock.EmitInstantiableBlock()
   at Bridge.Translator.ClassBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.GenerateScript.Execute()	ReflectionLambdaIssue	c:\users\greg\documents\visual studio 2017\Projects\ReflectionLambdaIssue\Program.cs	8

**Comment by vladsch** [comment]
Hi,

Such issue is already fixed in v16
See https://github.com/bridgedotnet/Bridge/issues/2605

**Comment by geoffreymcgill** [comment]
Hi @rufio620 – If possible, it would be best to create a sample in https://dev.deck.net to test.
