### ISSUE TITLE
Unused labels crash compiler

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2692]
Unused labels crash compiler.

### Steps To Reproduce

https://dev.deck.net/a80439e6a6c7cf8209dfc98df9941cad

```c#
public class Program
{
    public static void Main()
    {
        Try:
        int value = 7;
    }
}
```

### Actual Result
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Bridge.Translator.Emitter.VisitLabelStatement(LabelStatement labelStatement)
   at ICSharpCode.NRefactory.CSharp.LabelStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.Block.<>c__DisplayClass51_0.<DoEmitBlock>b__0(AstNode child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Bridge.Translator.Block.DoEmitBlock()
   at Bridge.Translator.Block.EmitBlock()
   at Bridge.Translator.Block.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
```

**Comment by geoffreymcgill** [comment]
Excellent bug. We will fix this.
