### ISSUE TITLE
Enhance same key exception to properly report which type was duplicated

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2796]
Exception thrown when a duplicated type found:
```
Severity	Code	Description	Project	File	Line	Source	Suppression State
Error		Error: An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Bridge.Translator.Translator.AddNestedTypes(IEnumerable`1 types)
   at Bridge.Translator.Translator.ReadTypes(AssemblyDefinition assembly)
   at Bridge.Translator.Translator.InspectReferences()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Translator.TranslatorProcessor.Process()
   at Bridge.Build.BridgeCompilerTask.Execute()	UnityEngine			Build	
```

Correct exception message to show the type name causing the duplicated problem.

**Comment by vladsch** [comment]
Please use latest source code from master, such possible issue is handled with more meaningful message (you can understand which type causes the exception)

**Comment by vladsch** [comment]
Also, it can be the same issue https://github.com/bridgedotnet/Bridge/issues/2758
If you use Bridge.Collections then remove that reference because the code is ported to Bridge.

**Comment by TriEdgeAI** [comment]
I was using the version tagged Bridge v16-beta2 and added the error message myself.

**Comment by TriEdgeAI** [comment]
I figured it out, I'll make a PR in a few minutes.

**Comment by michaelcheers** [comment]
@TriEdgeAI, I am getting the same error message and I don't think I have any nested classes. I have attached my project. Could you help me find this error?
[My Project](https://github.com/bridgedotnet/Bridge/files/1085675/MonoGameForBridge.zip)

**Comment by TriEdgeAI** [comment]
I can try. :)

**Comment by TriEdgeAI** [comment]
Can you give me the callstack? Are you on the latest version of master?
