### ISSUE TITLE
Nested class named 'Name' is wrong, is it OK?

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#2955]
### Steps To Reproduce

https://deck.net/5c6c4092fe14c0963c712f300607bdb8

```c#
public class Program
{
    protected abstract class Validation
    {
        private static class Options
        {
            public static class Name
            {
                public const int Minimum = 2;
                public const int Maximum = 400;
            }
        }
    }

    public static void Main()
    {
        var msg = "Hello, World!";
        
        Console.WriteLine(msg);
    }
}

```

### Expected Result

```
Built successfully...
```

### Actual Result

```
Exception:
Bridge.Contract.EmitterException: Nested class cannot have such name: Name. Please rename it.
   at Bridge.Translator.Inspector.VisitTypeDeclaration(TypeDeclaration typeDeclaration)
   at Bridge.Translator.Inspector.VisitTypeDeclaration(TypeDeclaration typeDeclaration)
   at Bridge.Translator.Inspector.VisitTypeDeclaration(TypeDeclaration typeDeclaration)
   at Bridge.Translator.Inspector.VisitTypeDeclaration(TypeDeclaration typeDeclaration)
   at ICSharpCode.NRefactory.CSharp.TypeDeclaration.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Contract.Helpers.AcceptChildren(AstNode node, IAstVisitor visitor)
   at Bridge.Translator.Inspector.VisitNamespaceDeclaration(NamespaceDeclaration namespaceDeclaration)
   at ICSharpCode.NRefactory.CSharp.NamespaceDeclaration.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Contract.Helpers.AcceptChildren(AstNode node, IAstVisitor visitor)
   at Bridge.Translator.Inspector.VisitSyntaxTree(SyntaxTree node)
   at Bridge.Translator.Translator.InspectTypes(MemberResolver resolver, IAssemblyInfo config)
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
```

**Comment by michaelcheers** [comment]
@hardhub, this is a very interesting bug.

**Comment by vladsch** [comment]
See https://github.com/bridgedotnet/Bridge/issues/2961#issuecomment-318646411

**Comment by hardhub** [comment]
> The single change which we should change that only lower case name should be prefixed.

I think it is OK.
Considering all it is best option... to prefix only lower case "name".
It is much better than exception :)

**Comment by vladsch** [comment]
One note, we prefix members only. Class with 'name' naming (lower case) will throw an exception still
