### ISSUE TITLE
Interlocked class is marked unscriptable.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2982]
You cannot use the Interlocked class because of this error:
```
Bridge.Contract.EmitterException: Type System.Threading.Interlocked is marked as not usable from script
   at Bridge.Contract.BridgeTypes.ToJsName(IType type, IEmitter emitter, Boolean asDefinition, Boolean excludens, Boolean isAlias, Boolean skipMethodTypeParam, Boolean removeScope, Boolean nomodule, Boolean ignoreLiteralName, Boolean ignoreVirtual)
   at Bridge.Translator.MemberReferenceBlock.WriteSimpleTarget(ResolveResult resolveResult)
   at Bridge.Translator.MemberReferenceBlock.VisitMemberReferenceExpression()
   at Bridge.Translator.MemberReferenceBlock.EmitConversionExpression()
   at Bridge.Translator.ConversionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitMemberReferenceExpression(MemberReferenceExpression memberReferenceExpression)
   at ICSharpCode.NRefactory.CSharp.MemberReferenceExpression.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.InvocationBlock.VisitInvocationExpression()
   at Bridge.Translator.InvocationBlock.EmitConversionExpression()
   at Bridge.Translator.ConversionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitInvocationExpression(InvocationExpression invocationExpression)
   at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.ExpressionListBlock.EmitExpressionList(IEnumerable`1 expressions, Expression paramArg)
   at Bridge.Translator.ExpressionListBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.InvocationBlock.VisitInvocationExpression()
   at Bridge.Translator.InvocationBlock.EmitConversionExpression()
   at Bridge.Translator.ConversionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitInvocationExpression(InvocationExpression invocationExpression)
   at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.ExpressionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitExpressionStatement(ExpressionStatement expressionStatement)
   at ICSharpCode.NRefactory.CSharp.ExpressionStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.Block.<>c__DisplayClass51_0.<DoEmitBlock>b__0(AstNode child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Bridge.Translator.Block.DoEmitBlock()
   at Bridge.Translator.Block.EmitBlock()
   at Bridge.Translator.Block.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.VisitorMethodBlock.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.VisitorMethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.MethodBlock.EmitMethodsGroup(List`1 group)
   at Bridge.Translator.MethodBlock.EmitMethods(Dictionary`2 methods, Dictionary`2 properties, Dictionary`2 operators)
   at Bridge.Translator.MethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.ClassBlock.EmitStaticBlock()
   at Bridge.Translator.ClassBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.BridgeCompilerTask.Execute()	JSILTests.Testing			

```

**Comment by hardhub** [comment]
Maybe it is because of nature of single threaded JS....
Can it be wrapped in some way to avoid build error?

**Comment by TriEdgeAI** [comment]
I think it would be best if it's simply implemented with regular non-atomic operations for the sake of compatibility. JavaScript is single-threaded so it would never be a problem.
