### ISSUE TITLE
Combine scripts throws NullReferenceException in 16.0.1

### ISSUE THREAD

**Issue by desunit** [bridgedotnet/Bridge#3039]
I've updated the latest version of Bridget.NET (16.0.1) and started getting the following error for release build:
```
1>src\packages\Bridge.Min.16.0.1\build\Bridge.Min.targets(22,5): error : 2017-08-10T21:53:08:013 	Error		System.NullReferenceException: Object reference not set to an instance of an object.
1>src\packages\Bridge.Min.16.0.1\build\Bridge.Min.targets(22,5): error :    at Bridge.Translator.Translator.CombineProjectOutput(String fileName)
1>src\packages\Bridge.Min.16.0.1\build\Bridge.Min.targets(22,5): error :    at Bridge.Translator.TranslatorProcessor.PostProcess()
1>src\packages\Bridge.Min.16.0.1\build\Bridge.Min.targets(22,5): error :    at Bridge.Build.BridgeCompilerTask.Execute()
```

bridge.Release.json:
```
{
  "fileName" : "test.js",
  "combineScripts": true,
  "outputFormatting" : "Minified"
}
```

Removing the line:  outputFormatting fxes the problem.

**Comment by geoffreymcgill** [comment]
Hi @desunit Thanks for the report. We will investigate and try to fix right away.

**Comment by badcommandorfilename** [comment]
Hi, thanks for all your hard work!

Unfortunately, I'm getting `System.NullReferenceException: Object reference not set to an instance of an object.` on v16.0.4 of Bridge.NET.

After a fresh restart of Visual Studio 2015, it builds correctly _once_ - then every subsequent Build or Rebuild throws (stacktrace below). My project is quite large:

```
Resources:
    UIComponents.js                                   3183.587 KB
    Bridge.Resources.Parts.bridge.js                  1362.536 KB
    Bridge.Resources.Parts.bridge.meta.js              478.576 KB
    Bridge.Resources.Parts.newtonsoft.json.js           35.119 KB
    Bridge.Resources.Parts.Bridge.React.js             129.046 KB
    Bridge.Resources.Parts.Bridge.React.meta.js         53.119 KB
    Bridge.Resources.Parts.UIComponents.js            1074.127 KB
    UIComponents.min.js                               1491.986 KB
    Bridge.Resources.Parts.bridge.min.js               607.812 KB
    Bridge.Resources.Parts.bridge.meta.min.js          408.869 KB
    Bridge.Resources.Parts.newtonsoft.json.min.js       16.809 KB
    Bridge.Resources.Parts.Bridge.React.min.js          44.287 KB
    Bridge.Resources.Parts.Bridge.React.meta.min.js     44.812 KB
    Bridge.Resources.Parts.UIComponents.min.js         369.398 KB
```

```
at Microsoft.Ajax.Utilities.JSParser.ParseExpression(AstNode leftHandSide, Boolean single, Boolean bCanAssign, JSToken inToken)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionList(JSToken terminator)
   at Microsoft.Ajax.Utilities.JSParser.ParseMemberExpression(AstNode expression, List`1 newContexts)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseBlock()
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseWhileStatement()
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseBlock()
   at Microsoft.Ajax.Utilities.JSParser.ParseTryStatement()
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseFunctionBody(Block body)
   at Microsoft.Ajax.Utilities.JSParser.ParseFunction(FunctionType functionType, Context fncCtx)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseObjectLiteralProperty(Boolean isBindingPattern)
   at Microsoft.Ajax.Utilities.JSParser.ParseObjectLiteral(Boolean isBindingPattern)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseObjectLiteralProperty(Boolean isBindingPattern)
   at Microsoft.Ajax.Utilities.JSParser.ParseObjectLiteral(Boolean isBindingPattern)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseObjectLiteralProperty(Boolean isBindingPattern)
   at Microsoft.Ajax.Utilities.JSParser.ParseObjectLiteral(Boolean isBindingPattern)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionList(JSToken terminator)
   at Microsoft.Ajax.Utilities.JSParser.ParseMemberExpression(AstNode expression, List`1 newContexts)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseFunctionBody(Block body)
   at Microsoft.Ajax.Utilities.JSParser.ParseFunction(FunctionType functionType, Context fncCtx)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionList(JSToken terminator)
   at Microsoft.Ajax.Utilities.JSParser.ParseMemberExpression(AstNode expression, List`1 newContexts)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseStatements(Block block)
   at Microsoft.Ajax.Utilities.JSParser.InternalParse()
   at Microsoft.Ajax.Utilities.JSParser.Parse(DocumentContext sourceContext)
   at Microsoft.Ajax.Utilities.Minifier.MinifyJavaScript(String source, CodeSettings codeSettings)
   at Bridge.Translator.Translator.Minify(Minifier minifier, String source, CodeSettings settings)
   at Bridge.Translator.Translator.Minify(TranslatorOutputItem output, CodeSettings minifierSettings)
   at Bridge.Translator.Translator.Minify(IEnumerable`1 outputs, Func`2 minifierSettingsResolver)
   at Bridge.Translator.Translator.Minify()
   at Bridge.Translator.TranslatorProcessor.PostProcess()
   at Bridge.Build.BridgeCompilerTask.Execute()	UIComponents			
```

bridge.json:
```
{
  // The folder to output JavaScript (.js) files.
  "output": "../../Web/Scripts/bridge",
  "combineScripts": true,
  // Enable the Bridge Console.
  // Default is false.
  "console": {
    "enabled": false
  },

  // Enable browser debugging of C# files.
  // Default is false.
  "sourceMap": {
    "enabled": true
  },

  // Set to true to disable Reflection metadata generation.
  // Default is false.
  "reflection": {
    "disabled": false
  },

  // Generate TypeScript Definition (.d.ts) files.
  // Default is false.
  "generateTypeScript": false,

  // Delete everything from the output folder
  // Default is false
  "cleanOutputFolderBeforeBuild": false,

  // Set to false to disable Report generation.
  // Default is false.
  "report": {
    "enabled": true
  }

  // More config options available at
  // https://github.com/bridgedotnet/Bridge/wiki/global-configuration
}
```

**Comment by geoffreymcgill** [comment]
Hi @badcommandorfilename – Any chance you could update to the latest Bridge release and retest? Currently **16.4.1**.

**Comment by badcommandorfilename** [comment]
Hi again,

Did a bit more experimenting and added the following to bridge.json:

```
"combineScripts": true,
"outputFormatting": "Formatted",
"logging": {
    "level": "Trace"
}
```

The project now builds, so I suspect the problem was specifically to do with the minified output.

Also, the above note about it building once was wrong - it never built, but the error message only showed on the second failure.

Additionally, the un-minified output has a parsing error:

```
                    var plugins = System.Array.init([new UIComponents.Components.Plugins.AlloyMenu.EmbedYoutubePlugin()], UIComponents.Components.Plugins.AlloyMenu.EmbedYoutubePlugin);

                    $t = Bridge.getEnumerator(plugins);
                    try {
                        while ($t.moveNext()) {
                            var plugin = $t.Current;

                            UIComponents.Components.Plugins.AlloyMenu.AlloyPlugin.registerPlugin(?, plugin, alloyhandle);

                        }
                    } finally {
                        if (Bridge.is($t, System.IDisposable)) {
                            $t.System$IDisposable$dispose();
                        }
                    }
                    return editor;
```

Note the "?" in the output. Is it safe to assume that this error was just the symptom of trying to minify broken generated output? I can attach the build log if it helps!

Thanks!

**Comment by geoffreymcgill** [comment]
@badcommandorfilename – What version of Bridge are you using?

**Comment by badcommandorfilename** [comment]
Hi @geoffreymcgill - thanks for your help!

It was a typo before, I was originally on v16.4.0 but I just upgraded to v16.4.1 after your last comment. Current package.config is:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Bridge" version="16.4.1" targetFramework="net461" />
  <package id="Bridge.Core" version="16.4.1" targetFramework="net461" />
  <package id="Bridge.Html5" version="16.4.1" targetFramework="net461" />
  <package id="Bridge.Html5.Console" version="1.0.4" targetFramework="net461" />
  <package id="Bridge.Min" version="16.4.1" targetFramework="net461" />
  <package id="Bridge.Newtonsoft.Json" version="1.2.2" targetFramework="net461" />
  <package id="Bridge.React" version="3.1.5" targetFramework="net461" />
</packages>
```

v16.4.1 still generates:
```
UIComponents.Components.Plugins.AlloyMenu.AlloyPlugin.registerPlugin(?, new UIComponents.Components.Plugins.AlloyMenu.EmbedYoutubePlugin(), alloyhandle);
```

from the input
```csharp
AlloyPlugin.RegisterPlugin(new EmbedYoutubePlugin(), alloyhandle);
```

**Comment by geoffreymcgill** [comment]
@badcommandorfilename – I tested with the settings originally presented in this thread everything appears to be working fine. This might be a new issue, so please create a new Issue and we'll continue the discussion there. 

As well, in the new Issue, we're going to need a simplified project that demonstrates how to reproduce. Can you create a simplified project and send us a link to the GitHub repo? Or provide instructions on how to reproduce.

**Comment by badcommandorfilename** [comment]
Ok, no problem - I think this is related to an error that should be caught by the compiler but instead tries to generate some bad output that then throws during minification.

I'll see if my problem matches any other issues and create a new one with a repro if I can.

Thanks again for your help!

**Comment by geoffreymcgill** [comment]
My first guess is an issue with the `[Template]` on `registerPlugin`. But that just a guess. 

Starting a new Issue and providing a simplified sample demonstrating how to reproduce would be best.
