### ISSUE TITLE
Type aliases for generic types do not work

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3264]
Type aliases for generic types do not work. The issue doesn't affect non-generic types.

### Steps To Reproduce

https://deck.net/8928eaa1f029ef8cebc25bfa3adeb758

```csharp
namespace Demo
{
    using System;
    using Test = Ext.Root.Test<string>;
    
    public class Program
    {
        public static void Main()
        {
            var test = new Test();
        }
    }
}

namespace Ext
{
    using Bridge;

    [External]
    public static class Root
    {
        public class Test<T>
        {
        }
    }
}
```

### Expected Result

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.Program", {
        main: function Main () {
            var test = new Ext.Root.Test();
        }
    });
});
```

### Actual Result

```js
C# to JavaScript Compilation Failed

System.NullReferenceException: Object reference not set to an instance of an object.
   at Bridge.Translator.Emitter.GetTypeDefinition(AstType reference, Boolean safe)
   at Bridge.Translator.ObjectCreateBlock.VisitObjectCreateExpression()
   at Bridge.Translator.ObjectCreateBlock.EmitConversionExpression()
   at Bridge.Translator.ConversionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitObjectCreateExpression(ObjectCreateExpression objectCreateExpression)
   ...
```

**Comment by fabriciomurta** [comment]
Issue's fix merged upstream! Will be available on next bridge release (see milestone).
