### ISSUE TITLE
IConvertible not working properly.

### ISSUE THREAD

**Issue by Equijano24** [bridgedotnet/Bridge#3300]
A description of the issue.

### Steps To Reproduce

http://deck.net/ <-- Replace with a link to your Deck

```csharp
public class Program
{
    public static void Main()
    {
        object val = 1;
        Console.WriteLine(((IConvertible)val).ToDouble(null));
    }
}
```

### Expected Result

```js
1
```

### Actual Result

```js
System.Exception: TypeError: Cannot read property '$kind' of undefined
    at Object.is (https://deck.net/resources/js/bridge/bridge.min.js?16.5.0:7:8596)
    at Object.cast (https://deck.net/resources/js/bridge/bridge.min.js?16.5.0:7:9857)
    at Function.Main (https://deck.net/RunHandler.ashx?h=1293864056:10:66)
    at https://deck.net/resources/js/bridge/bridge.min.js?16.5.0:7:38586
    at HTMLDocument.i (https://deck.net/resources/js/bridge/bridge.min.js?16.5.0:7:5163)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)
    at n.fn.init.n.fn.ready (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:29515)
    at new n.fn.init (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:24945)
    at n (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:405)
```

**Comment by michaelcheers** [comment]
Create deck and dot net fiddle links:

- https://deck.net/f4c5c891ab6613d56d327c4ad363e787/third
- https://dotnetfiddle.net/XiCYdd

should throw no exception.
