### ISSUE TITLE
Inline metadata location and Modules

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3347]
The issue is reproducible in a program declaring a module and consuming it, when **bridge.json** contains the following options:
```js
"reflection": {
  "disabled": false,
  "target": "Inline" 
},
```
Currently inline metadata is being written after the last entity definition in a namespace (definitions are ordered alphabetically: A->Z). If the last entity is a module, then the metadata will be placed inside the module definition, but at that point entities will not be created yet, because of the execution order. 

In other words, if entities use a module (the defined one, or any other), they will be wrapped in `require(["Module"], function(m) { .... } );` function. That function has a callback where all entities are defined and actually will be created. But before that the module must be resolved first. And if the metadata is located in the module definition function, then it will be executed too early. That causes an error.

The sample below demonstrates the described problem. In order to fix it, we can add an empty class `class Z { }`, that will get the last position when ordered - and metadata will be placed in the right block.

### Steps To Reproduce

https://deck.net/6616d9c01c51bdf020e44556e00c934e

```csharp
public class Demo
{
    public static void Main()
    {
        var t = new MyModuleRoot.TestClass();
        t.SayHello();
    }
}

[Module(ModuleType.AMD, "MyModule")]
public static class MyModuleRoot
{
    public class TestClass
    {
        public void SayHello() 
        {
            Console.WriteLine("Hello, world!");
        }
    }
}
```

### Expected Result

Console output:
```
> Hello, world!
```

### Actual Result

```js
System.Exception: ReferenceError: Demo is not defined
    at https://deck.net/RunHandler.ashx?h=-2088935320:48:26
    at Object.execCb (https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.js:1696:33)
    at Module.check (https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.js:883:51)
    at Module.enable (https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.js:1176:22)
    at Object.enable (https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.js:1557:39)
    at Module.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.js:1161:33)
    at https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.js:134:23
    at each (https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.js:59:31)
    at Module.enable (https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.js:1113:17)
    at Module.init (https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.js:788:26)
```

### See Also
- [Retyped/Retyped#39] usage of Retyped.React breaks bridge reflection

**Comment by fabriciomurta** [comment]
The fix has been merged upstream, it will be available to the next Bridge version (currently 16.7.0)!
