### ISSUE TITLE
Dictionary failure for ulong index.

### ISSUE THREAD

**Issue by Equijano24** [bridgedotnet/Bridge#3363]
A description of the issue.

### Steps To Reproduce

https://deck.net/023233426ee87977ee47e71a024f0efb

https://dotnetfiddle.net/0VBxBb

```csharp
public class Program
{
    public static void Main()
    {
        IDictionary<ulong, string> dic = new Dictionary<ulong, string>();        
        
        dic.Add(20, "Diez");
        dic.Add(10, "Diez");
        dic.Add(30, "Diez");
        
        Console.WriteLine(dic.Keys.Min());
        Console.WriteLine(dic[10]);
        Console.WriteLine(dic[dic.Keys.Min()]);
    }
}
```

### Expected Result

```js
10
Diez
Diez
```

### Actual Result

```js
10
Diez
System.Exception: Uncaught System.Collections.Generic.KeyNotFoundException: Key 10 does not exist.
Error: Key 10 does not exist.
    at ctor (https://deck.net/resources/js/bridge/bridge.min.js?16.6.1:7:87519)
    at new ctor (https://deck.net/resources/js/bridge/bridge.min.js?16.6.1:7:91746)
    at ctor.get (https://deck.net/resources/js/bridge/bridge.min.js?16.6.1:7:243634)
    at Function.Main (https://deck.net/RunHandler.ashx?h=1819978463:17:42)
    at https://deck.net/resources/js/bridge/bridge.min.js?16.6.1:7:39403
    at HTMLDocument.i (https://deck.net/resources/js/bridge/bridge.min.js?16.6.1:7:5182)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)
    at n.fn.init.n.fn.ready (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:29515)
    at new n.fn.init (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:24945)
```

**Comment by geoffreymcgill** [comment]
Hi @Equijano24 – Thanks for the report and excellent sample demonstrating how to reproduce the defect. We will investigate and try to fix right away.

**Comment by fabriciomurta** [comment]
Fixed and merged upstream! The fix will make it to next Bridge release! (currently, 16.7.0)
