### ISSUE TITLE
Convert.ToChar fails when converting from object

### ISSUE THREAD

**Issue by Equijano24** [bridgedotnet/Bridge#3385]
Assigning a char to object and then invoking Convert.ToChar on it throws an exception.

### Steps To Reproduce

https://deck.net/712252a7e05755c5a602d767c3ee9328

```csharp
public class Program
{
    public static void Main()
    {
        object a = 'a';
        Console.WriteLine(Convert.ToChar(a));
    }
}
```

### Expected Result

```js
a
```

### Actual Result

```js
System.Exception: Uncaught System.InvalidCastException: Invalid cast from 'Object' to 'Char'.
Error: Invalid cast from 'Object' to 'Char'.
    at ctor (https://deck.net/resources/js/bridge/bridge.min.js?16.7.0:7:88149)
    at new ctor (https://deck.net/resources/js/bridge/bridge.min.js?16.7.0:7:93335)
    at Object.throwInvalidCastEx (https://deck.net/resources/js/bridge/bridge.min.js?16.7.0:7:325127)
    at Object.toChar (https://deck.net/resources/js/bridge/bridge.min.js?16.7.0:7:305220)
    at Function.Main (https://deck.net/RunHandler.ashx?h=-2003126879:10:73)
    at https://deck.net/resources/js/bridge/bridge.min.js?16.7.0:7:39626
    at HTMLDocument.i (https://deck.net/resources/js/bridge/bridge.min.js?16.7.0:7:5182)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)
    at n.fn.init.n.fn.ready (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:29515)
```

**Comment by fabriciomurta** [comment]
The pull request with fixes resolving this issue has just been merged upstream! The fix will be available next Bridge version (see attached milestone).
