### ISSUE TITLE
Error when 'using static' statement wrapped with #if directive

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3421]
Bridge fails to process `using static` statement wrapped with `#if - #endif` directives. The error occurs only when a symbol is defined, so in the example below the project can be built in **Release** configuration, but fails in **Debug** configuration.

### Steps To Reproduce

```csharp
using System;

#if DEBUG
using static Demo.Logger;
#endif

namespace Demo
{
    public class Program
    {
        public static void Main()
        {
#if DEBUG
            Log("Success");
#endif
        }
    }

    public static class Logger
    {
        public static void Log(string msg)
        {
            Console.WriteLine();
        }
    }
}
```

### Expected Result (Debug)

```js
Bridge.assembly("ClassLibrary1", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.Logger", {
        statics: {
            methods: {
                Log: function (msg) {
                    System.Console.WriteLine();
                }
            }
        }
    });

    Bridge.define("Demo.Program", {
        main: function Main () {
            Demo.Logger.Log("Success");
        }
    });
});
```

### Actual Result (Debug)

Compilation error:
```
  Error: 2018-02-16T16:49:52:768 	Error		One or more errors occurred.    at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Bridge.Translator.Translator.BuildSyntaxTree()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.BridgeCompilerTask.Execute() (1, 1)
```

**Comment by fabriciomurta** [comment]
Fixed and merged upstream! This will make it to next Bridge release! (refer to issue milestone, currently 16.8.0).
