### ISSUE TITLE
Compiler throws error while compiling class that passes nested class as type argument to interface

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#3467]
When compiling a class where a type parameter is being passed to an interface there's a compilation error if the class specified in the type parameter is imported statically, rather than specifying the full path.

Here's a simple reproduce case that demonstrates the issue with a single class, which hopefully makes this clearer:

[ClassStaticUsingBug.zip](https://github.com/bridgedotnet/Bridge/files/1803693/ClassStaticUsingBug.zip)

This appears to only be the case if the configuration option `outputFormatting` is *Minified*.

Here's the error that's produced:
```
Error		Object reference not set to an instance of an object.    at Microsoft.Ajax.Utilities.JSParser.ParseExpression(AstNode leftHandSide, Boolean single, Boolean bCanAssign, JSToken inToken)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionList(JSToken terminator)
   at Microsoft.Ajax.Utilities.JSParser.ParseMemberExpression(AstNode expression, List`1 newContexts)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseArrayLiteral(Boolean isBindingPattern)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseObjectLiteralProperty(Boolean isBindingPattern)
   at Microsoft.Ajax.Utilities.JSParser.ParseObjectLiteral(Boolean isBindingPattern)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionList(JSToken terminator)
   at Microsoft.Ajax.Utilities.JSParser.ParseMemberExpression(AstNode expression, List`1 newContexts)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseFunctionBody(Block body)
   at Microsoft.Ajax.Utilities.JSParser.ParseFunction(FunctionType functionType, Context fncCtx)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionList(JSToken terminator)
   at Microsoft.Ajax.Utilities.JSParser.ParseMemberExpression(AstNode expression, List`1 newContexts)
   at Microsoft.Ajax.Utilities.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at Microsoft.Ajax.Utilities.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at Microsoft.Ajax.Utilities.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at Microsoft.Ajax.Utilities.JSParser.ParseStatements(Block block)
   at Microsoft.Ajax.Utilities.JSParser.InternalParse()
   at Microsoft.Ajax.Utilities.JSParser.Parse(DocumentContext sourceContext)
   at Microsoft.Ajax.Utilities.Minifier.MinifyJavaScript(String source, CodeSettings codeSettings)
   at Bridge.Translator.Translator.Minify(Minifier minifier, String source, CodeSettings settings)
   at Bridge.Translator.Translator.Minify(TranslatorOutputItem output, CodeSettings minifierSettings)
   at Bridge.Translator.Translator.Minify(IEnumerable`1 outputs, Func`2 minifierSettingsResolver)
   at Bridge.Translator.Translator.Minify()
   at Bridge.Translator.TranslatorProcessor.PostProcess()
   at Bridge.Build.BridgeCompilerTask.Execute()	ClassStaticUsingBug			Build	
```

**Comment by fabriciomurta** [comment]
Albeit this runs on deck with an error, the single file approach (by just copypasting deck into a file in a Bridge project) reproduces the same issue while building the project: https://deck.net/649221441d20e522339078d287abbf03

So no project needed to reproduce the issue. Still reproducible now in Bridge 17.4.0. Important: As mentioned, `OutputFormatting` option should be either `Minified` or `Both` to trigger the error.
Deck outputs minified files, yet it works (with erroneous output code).

**Comment by fabriciomurta** [comment]
Fixed! The fix will make it to the next Bridge release!
