### ISSUE TITLE
Delegate with covariant type parameter in Expression

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3484]
Bridge throws an exception when trying to cast **Expression.Body** to an actual expression type - (**NewExpression** in the sample below). The error is reproducible for a delegate with a covariant generic type parameter, when a derived type was used as a type argument.

### Steps To Reproduce

https://deck.net/8bdd3fbbf50b642134db1c9642a52568

```csharp
using System;
using System.Linq.Expressions;
using Bridge;

public class Program
{
    public static void Main()
    {
        var name1 = GetTypeName(() => new A());
        Console.WriteLine(name1);
        
        var name2 = GetTypeName(() => new B());
        Console.WriteLine(name2);
    }
    
    public static string GetTypeName(Expression<Func<A>> expr)
    {
        var newExpr = (NewExpression) expr.Body;
        return newExpr.Type.FullName;
    }
}

public class A
{
}

public class B : A
{
}
```

### Expected Result

https://dotnetfiddle.net/OwmJov

Console output
```
A
B
```

### Actual Result

Console output
```
A
System.Exception: Uncaught System.InvalidCastException: Unable to cast type System.Object to type Boolean
Error: Unable to cast type System.Object to type Boolean
    at ctor (https://deck.net/resources/js/bridge/bridge.min.js?16.8.2:7:88705)
    at new ctor (https://deck.net/resources/js/bridge/bridge.min.js?16.8.2:7:93891)
    at Object.cast (https://deck.net/resources/js/bridge/bridge.min.js?16.8.2:7:10290)
    at Function.GetTypeName (https://deck.net/RunHandler.ashx?h=-2138153307:22:59)
    at Function.Main (https://deck.net/RunHandler.ashx?h=-2138153307:15:33)
    at https://deck.net/resources/js/bridge/bridge.min.js?16.8.2:7:40150
    at HTMLDocument.i (https://deck.net/resources/js/bridge/bridge.min.js?16.8.2:7:5505)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)
    at n.fn.init.n.fn.ready (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:29515)
```

**Comment by AndreyChechel** [comment]
When unsafe casting using `As<>()` method is used, a wrong value is returned:

https://deck.net/03a7460cf97dc44cbb7c78252245da33

```cs
public static string GetTypeName(Expression<Func<A>> expr)
{
    var newExpr = expr.Body.As<NewExpression>();
    return newExpr.Type.FullName;
}
```

Console output
```
A
A
```
