### ISSUE TITLE
Init empty jqXHR array fails since is not defined in Bridge.jQuery

### ISSUE THREAD

**Issue by kcudnik** [bridgedotnet/Bridge#3524]
Init empty jqXHR array fails since is not defined in Bridge.jQuery

### Steps To Reproduce

https://deck.net/9f174d825b3b5bdc7c3aa6398c76262a

```csharp
public class Program
{
    public static void Main()
    {
        jqXHR[] deferreds = { };
    }
}
```

### Expected Result

```js
code runs fine
```

### Actual Result

```js
System.Exception: TypeError: Cannot read property 'jqXHR' of undefined
    at Function.Main (https://deck.net/RunHandler.ashx?h=1804941215:9:65)
    at https://deck.net/resources/js/bridge/bridge.min.js?16.8.2:7:40150
    at HTMLDocument.i (https://deck.net/resources/js/bridge/bridge.min.js?16.8.2:7:5505)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)
    at n.fn.init.n.fn.ready (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:29515)
    at n.fn.init (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:24945)
    at n (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:405)
    at Object.ready (https://deck.net/resources/js/bridge/bridge.min.js?16.8.2:7:5568)
    at https://deck.net/resources/js/bridge/bridge.min.js?16.8.2:7:40129
```

**Comment by geoffreymcgill** [comment]
Hi @kcudnik – Can you post this issue in the Frameworks repo?

https://github.com/bridgedotnet/Frameworks/issues

**Comment by kcudnik** [comment]
Done https://github.com/bridgedotnet/Frameworks/issues/78
