### ISSUE TITLE
Unused local function throws NullReferenceException

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#3558]
If a Local Function is defined but not used, a NullReferenceException is thrown.

### Steps To Reproduce

https://deck.net/2c51fd6142dabe51aa36b76e0d094f49

```csharp
public class Program
{
    public static void Main()
    {
        var a = 15;
        bool test() => a > 10;
        
        // Uncomment to make it working:
        //if(test())
        {
            Console.WriteLine("true");
        }
    }
}
```

### Expected Result

```
true
```

### Actual Result

```
C# to JavaScript Compilation Failed

System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Bridge.Translator.LocalFunctionReplacer.Replace(SyntaxNode root, SemanticModel model)
   at Bridge.Translator.SharpSixRewriter.Rewrite(Int32 index)
   at Bridge.Translator.Translator.<>c__DisplayClass91_1.<Rewrite>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Bridge.Translator.Translator.Rewrite()
   at Bridge.Translator.Translator.BuildSyntaxTree()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Bridge.Translator.LocalFunctionReplacer.Replace(SyntaxNode root, SemanticModel model)
   at Bridge.Translator.SharpSixRewriter.Rewrite(Int32 index)
   at Bridge.Translator.Translator.<>c__DisplayClass91_1.<Rewrite>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

```

## See Also

* https://github.com/bridgedotnet/Bridge/issues/3557
* https://github.com/bridgedotnet/Bridge/issues/3550

**Comment by fabriciomurta** [comment]
Fixed! This specific issue will make it to next Bridge release (see attached milestone).
