### ISSUE TITLE
nested functions with variable number of parameters do not work

### ISSUE THREAD

**Issue by emumanu** [bridgedotnet/Bridge#3566]
Nested functions work as long as you don't use variable number of parameters

### Steps To Reproduce

https://deck.net/b2b205ca0b3c13512a1011ad9ae5f63a

```csharp
using System;

public class Program
{
    public static void Main()
    {
        int add(int a, int b, params object[] vals)
        {
            return a + b;
        }
		
        Console.WriteLine(add(1,2));
    }
}
```

You can see that it is working in c#:

https://dotnetfiddle.net/daVT7v

### Actual Result

```
C# to JavaScript Compilation Failed

System.AggregateException: One or more errors occurred. ---> System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Bridge.Translator.Translator.<>c__DisplayClass92_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Bridge.Translator.Translator.BuildSyntaxTree()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
---> (Inner Exception #0) System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Bridge.Translator.Translator.<>c__DisplayClass92_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by geoffreymcgill** [comment]
@emumanu Thanks for the report. We are working on supporting this syntax variation right now and will include within the Bridge [17.1.0](https://github.com/bridgedotnet/Bridge/milestone/60) release.

**Comment by emumanu** [comment]
Thank you @geoffreymcgill

**Comment by vladsch** [comment]
Fixed in https://github.com/bridgedotnet/Bridge/pull/3567

**Comment by emumanu** [comment]
Wow, that was fast @vladsch. Thanks!

**Comment by fabriciomurta** [comment]
The fix was just merged upstream, and should be available next Bridge release (see attached milestone).
