### ISSUE TITLE
Error on boxing of nullable enums

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3612]
Runtime error occurs when boxing a nullable enum value. 
The issue is not reproducible for nullable structures and primitive types.

### Steps To Reproduce

https://deck.net/3856bbc6c0a0e14fb86ab0f2beafa40e

```csharp
[Rules(Boxing = BoxingRule.Managed)]
public class Program
{
    public static void Main()
    {
        SetModeStronglyTyped(null);
    }

    public static void SetModeStronglyTyped(Mode? mode)
    {
        SetMode(mode);
    }

    public static void SetMode(object mode)
    {
        Console.WriteLine(mode ?? "Null");
    }
}

public enum Mode
{
    Slow,
    Medium,
    Fast
} 
```

### Expected Result

Console output:
```
Null
```

### Actual Result

Console output:
```
System.Exception: Uncaught System.NullReferenceException: instance is null
Error: instance is null
    at $ctor1.ctor (https://deck.net/resources/js/bridge/bridge.min.js?17.1.0:7:89931)
    at $ctor1 (https://deck.net/resources/js/bridge/bridge.min.js?17.1.0:7:91024)
    at new $ctor1 (https://deck.net/resources/js/bridge/bridge.min.js?17.1.0:7:610815)
    at Object.getType (https://deck.net/resources/js/bridge/bridge.min.js?17.1.0:7:20269)
    at Function.SetModeStronglyTyped (https://deck.net/RunHandler.ashx?h=-328818050:25:127)
    at Function.Main (https://deck.net/RunHandler.ashx?h=-328818050:20:26)
    at https://deck.net/resources/js/bridge/bridge.min.js?17.1.0:7:41190
    at HTMLDocument.i (https://deck.net/resources/js/bridge/bridge.min.js?17.1.0:7:5796)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)
```

### See also
- https://forums.bridge.net/forum/bridge-net-pro/bugs/5481-urgent-nullreferenceexception-when-passing-null-into-a-nullable-enum-parameter

**Comment by fabriciomurta** [comment]
Fixed! This will be included in next Bridge release!
