### ISSUE TITLE
bridge.exe fails when dependent assembly built in release mode

### ISSUE THREAD

**Issue by groogiam** [bridgedotnet/Bridge#3641]
I am running bridge.exe from the command line with a prebuilt bridge dll.

Below is log output for the error I get when I reference the release mode dll.

Executing Bridge.Builder.Console...
2018-06-18T00:15:05:505 	Info		Translating...
2018-06-18T00:15:05:513 	Info		Inspecting references...
2018-06-18T00:15:05:831 	Info		Inspecting references done
2018-06-18T00:15:05:860 	Info		Product info:
2018-06-18T00:15:05:866 	Info			Bridge.Compiler version 16.7.0
2018-06-18T00:15:05:872 	Info			[Bridge Framework, version 16.7.0]
2018-06-18T00:15:05:877 	Info			Copyright 2008-2018 Object.NET, Inc.
2018-06-18T00:15:05:892 	Info		Discovering plugins...
2018-06-18T00:15:05:906 	Info		Will use the following plugin path "C:\Temp\BuildTest\gxncfi3h.sjp\Bridge\plugins"
2018-06-18T00:15:05:912 	Info		The plugin path does not exist. Skipping searching test framework plugins in the plugin folder.
2018-06-18T00:15:05:923 	Info		No AssemblyCatalogs found
2018-06-18T00:15:05:930 	Info		Reading plugin configs...
2018-06-18T00:15:05:939 	Info		Reading plugin configs done
2018-06-18T00:15:05:946 	Info		Building syntax tree...
2018-06-18T00:15:07:791 	Info		Building syntax tree done
2018-06-18T00:15:07:823 	Info		Assembly definition to references...
2018-06-18T00:15:08:551 	Info		Assembly definition to references done
2018-06-18T00:15:08:688 	Info		Inspecting types...
2018-06-18T00:15:08:770 	Info		Inspecting types done
2018-06-18T00:15:08:778 	Info		Creating emitter...
2018-06-18T00:15:08:846 	Info		Creating emitter done
2018-06-18T00:15:08:858 	Info		Before emitting...
2018-06-18T00:15:08:865 	Info		Before emitting done
2018-06-18T00:15:08:873 	Info		Emitting...
2018-06-18T00:15:09:386 	Info		Transforming outputs...
2018-06-18T00:15:09:407 	Info		Transforming outputs done
2018-06-18T00:15:09:414 	Info		Emitting done
2018-06-18T00:15:09:422 	Info		After emitting...
2018-06-18T00:15:09:429 	Info		After emitting done
2018-06-18T00:15:09:434 	Info		Translating done
2018-06-18T00:15:09:442 	Info		Post processing...
2018-06-18T00:15:09:449 	Info		outputPath is C:\Temp\BuildTest\gxncfi3h.sjp\
2018-06-18T00:15:09:461 	Info		projectPath is C:\Temp\BuildTest
2018-06-18T00:15:09:468 	Info		Extracting core scripts...
2018-06-18T00:15:09:478 	Info		Extracting resources...
2018-06-18T00:15:09:511 	Info		Skipping resource bridge.console.js as it has setting resources.extract != true
2018-06-18T00:15:09:521 	Info		Done extracting resources
2018-06-18T00:15:09:571 	Info		Skipping extracting Locales
2018-06-18T00:15:09:578 	Info		Done extracting core scripts
2018-06-18T00:15:10:741 	Error		Bridge.NET Compiler error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Ajax.Utilities.JSParser.ParseExpression(AstNode leftHandSide, Boolean single, Boolean bCanAssign, JSToken inToken)
   at Microsoft.Ajax.Utilities.JSParser.ParseVarDecl(JSToken inToken)
   at Microsoft.Ajax.Utilities.JSParser.ParseVariableStatement()
   at Microsoft.Ajax.Utilities.JSParser.ParseStatements(Block block)
   at Microsoft.Ajax.Utilities.JSParser.InternalParse()
   at Microsoft.Ajax.Utilities.Minifier.MinifyJavaScript(String source, CodeSettings codeSettings)
   at Bridge.Translator.Translator.Minify(Minifier minifier, String source, CodeSettings settings)
   at Bridge.Translator.Translator.Minify(TranslatorOutputItem output, CodeSettings minifierSettings)
   at Bridge.Translator.Translator.Minify(IEnumerable`1 outputs, Func`2 minifierSettingsResolver)
   at Bridge.Translator.Translator.Minify()
   at Bridge.Translator.TranslatorProcessor.PostProcess()
   at Bridge.Builder.Program.Main(String[] args)

**Comment by fabriciomurta** [comment]
Hello, @groogiam! Thanks for the report!

But that's too hard to say anything with the information you provided... Bridge NuGet packages are all published with Bridge in Release mode and Bridge.dll works fine in new projects, so I'm not sure what you are comparing with "Release" and "Debug" builds.

We'll mark this as invalid but if you have more information that could help us reproduce the issue, we'd be glad to review it.
