### ISSUE TITLE
String.IndexOf does not work properly for overload IndexOf(sub, startIndex, StringComparison)

### ISSUE THREAD

**Issue by serge-shaldanov** [bridgedotnet/Bridge#3679]
### Steps To Reproduce

https://deck.net/8798011b32415b49eccd55aec3da43a7

```csharp
public class Program
{
    public static void Main()
    {
        var msg = "Hello, World!";
        
        int i = msg.IndexOf("world", 3, StringComparison.InvariantCultureIgnoreCase);
        
        Console.WriteLine(i);
    }
}
```

### Expected Result

```js
var i = System.String.indexOf(msg, "world", 3, msg.length - 3, 3);
```

Result: 7

### Actual Result

```js
var i = System.String.indexOf(msg, "world", 3, msg.length, 3);
```
Result: 

> System.Exception: Uncaught System.ArgumentOutOfRangeException: Index and length must refer to a location within the string
Parameter name: length
Error: Index and length must refer to a location within the string
    at $ctor4.ctor (https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:91540)
    at $ctor4.$ctor1 (https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:92638)
    at $ctor4.$ctor3 (https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:572272)
    at new $ctor4 (https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:573754)
    at Function.indexOf (https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:287507)
    at Function.Main (https://deck.net/RunHandler.ashx?h=1139229282:11:35)
    at https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:42576
    at HTMLDocument.i (https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:6515)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)

**Comment by fabriciomurta** [comment]
Thanks for the report!

Deck with assert: https://deck.net/946f0c17f93ea351bd6bf822cb03b6fd
Dotnetfiddle: https://dotnetfiddle.net/ueBdiW

**Comment by fabriciomurta** [comment]
Fixed! The fix will make it to the next Bridge release! (check milestone)
