### ISSUE TITLE
JS version of int.Parse fails on some input data which are parsed fine in C#

### ISSUE THREAD

**Issue by serge-shaldanov** [bridgedotnet/Bridge#3682]
Hi, guys.

I'm find that the `int.Parse()` method can not parse some input data in JS code that considering as valid in C# code.

This is a case where we pass string containing trailing or leading space characters.

### Steps To Reproduce

Actual - Deck.net: https://deck.net/4bd94206f415b22c297e7e5d511bf20f

Expected - .NET Fiddle: https://dotnetfiddle.net/bd1mAM

```csharp
public class Program
{
    public static void Main()
    {
        Console.WriteLine(int.Parse(" 1"));
	Console.WriteLine(int.Parse("2 "));
	Console.WriteLine(int.Parse(" 3 "));
		
	Console.WriteLine(int.Parse("\t4"));
        Console.WriteLine(int.Parse("5\t"));
	Console.WriteLine(int.Parse("\t6\t"));
		
	Console.WriteLine(int.Parse("\r\n7"));
	Console.WriteLine(int.Parse("8\n"));
	Console.WriteLine(int.Parse("\r\n9\n"));
    }
}
```

### Expected Result

```js
1
2
3
4
5
6
7
8
9
```

### Actual Result

```js
System.Exception: Uncaught System.FormatException: Input string was not in a correct format.
Error: Input string was not in a correct format.
    at $ctor1.ctor (https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:91540)
    at $ctor1 (https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:92638)
    at new $ctor1 (https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:579885)
    at Function.parseInt (https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:121516)
    at Function.parse (https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:113509)
    at Function.Main (https://deck.net/RunHandler.ashx?h=1987598395:9:51)
    at https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:42576
    at HTMLDocument.i (https://deck.net/resources/js/bridge/bridge.min.js?17.2.0:7:6515)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)
```

**Comment by geoffreymcgill** [comment]
Hi @serge-shaldanov – Thanks for the report and excellent samples demonstrating how to reproduce the issue. We will review and attempt to fix right away.

**Comment by fabriciomurta** [comment]
Fixed! The fix will make it to the next Bridge release! Check milestone for the version it will effectively be available in.
