### ISSUE TITLE
Can not set values using references for dictionaries with value type of Action/Func.

### ISSUE THREAD

**Issue by Panzki** [bridgedotnet/Bridge#3731]
The anonymous lambda function for the key 0 in the `ActionMap` can be invoked as expected. However the action at key 1, which is passed as a references, can not be invoked. It looks like the problems is that the value can not be retrieved from the dictonary.
I tested this for `Dictionary<int, Func<bool>>` as well and it produces the same error.

### Steps To Reproduce

https://deck.net/7bbecf7a0fbb1019452b9869855e4bd0

```csharp
public class Program
{
    public static Dictionary<int, Action> ActionMap = new Dictionary<int, Action>(){
        {0, () => Console.WriteLine("Invoked Action at index 0.")},
        {1, MyAction}
    };
    
    private static Action MyAction = () => Console.WriteLine("Invoked Action at index 1.");
    
    public static void Main()
    {
        ActionMap[0]();
        ActionMap[1]();
    }
}
```

### Expected Result

```
> Invoked Action at index 0.
> Invoked Action at index 1.
```

### Actual Result

```
> Invoked Action at index 0.
> System.Exception: TypeError: Demo.Program.ActionMap.get(...) is not a function
    at Function.Main (https://deck.net/RunHandler.ashx?h=-1355312566:10:42)
    at https://deck.net/resources/js/bridge/bridge.min.js?17.3.0:7:42613
    at HTMLDocument.i (https://deck.net/resources/js/bridge/bridge.min.js?17.3.0:7:6515)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)
    at n.fn.init.n.fn.ready (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:29515)
    at new n.fn.init (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:24945)
    at n (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:405)
    at Object.ready (https://deck.net/resources/js/bridge/bridge.min.js?17.3.0:7:6578)
    at https://deck.net/resources/js/bridge/bridge.min.js?17.3.0:7:42586
```

**Comment by fabriciomurta** [comment]
I don't think the deck the way you shared works at all... Tried it on dotnet fiddle and it breaks in a similar way, with the first assertion being run.
- [Dotnet fiddle trying to run the test case](https://dotnetfiddle.net/ZOPHXF)

Some time ago dotnet fiddle used to have issues with some C#7.x language syntax, but this seems not to be the case here.
