### ISSUE TITLE
Please provide example how to use with webpack

### ISSUE THREAD

**Issue by chemaxa** [bridgedotnet/Bridge#3747]
I read about your https://github.com/bridgedotnet/Bridge/wiki/module-attribute but i dont understand how to use bundled code with webpack and standart ES6 imports/exports

When i build my code i getting 
 - bridge.js, 
 - newtonsoft.json.js,
 - demo.js

I put package.json in this files directory 
 ```
  "name": "demo",
  "version": "0.0.1",
  "main": "./bridge.js",
  "files": [
    "bridge.js",
    "bridge.d.ts",
    "bridge.meta.js",
    "newtonsoft.json.js",
    "demo.d.ts",
    "demo.js"
  ],

```
I try to import this into my react application bootstraped with [Create react app](https://github.com/facebook/create-react-app)

But it fail with error 
```
[at-loader] ./src/index.tsx:8:25
    TS2306: File 'D:/Repositories/demo/node_modules/demo/bridge.d.ts' is not a module.
````

I used this in my Assembly.cs 
```
using Bridge;
[assembly: Module("Demo")]
```

This is my bridge json

```
// See all bridge.json configuration options at:
// https://github.com/bridgedotnet/Bridge/wiki/global-configuration

{
  // The folder to output JavaScript (.js) files.
  "output": "$(OutDir)/bridge/",

  // Set to "Minified" to generate .min.js files.
  // Set to "Both" to generate both minified and non-minified .js files.
  // "Formatted" generates non-minified .js files.
  "outputFormatting": "Both",

  // Enable the Bridge Console.
  // Default is false.
  "console": {
    "enabled": false
  },

  // Enable browser debugging of C# files.
  // Default is false.
  "sourceMap": {
    "enabled": false
  },

  // Set to true to disable Reflection metadata generation.
  // Default is false.
  "reflection": {
    "disabled": true
  },

  // Generate TypeScript Definition (.d.ts) files.
  // Default is false.
  "generateTypeScript": true,

  // Delete everything from the output folder.
  // Default is false
  //        ** WARNING **
  // If true, all files within the "output"
  // folder location will be deleted on Build.
  //    ** USE WITH CAUTION **
  "cleanOutputFolderBeforeBuild": false,

  // Set to true to enable bridge.report.log generation.
  // Default is false.
  "report": {
    "enabled": false
  },

  // Rules to manage generated JavaScript syntax.
  // Default is "Managed"
  "rules": {
    "anonymousType": "Plain",
    "arrayIndex": "Managed",
    "autoProperty": "Plain",
    "boxing": "Managed",
    "externalCast": "Plain",
    "inlineComment": "Plain",
    "integer": "Managed",
    "lambda": "Plain"
  },

  // Automatically generate an index.html file
  // and add the file to the output directory.
  // Default is false.
  "html": {
    "disabled": false
  },

  // Add compilation logging to your Project.
  // Outputs a tab-delimited bridge.log file.
  // Set to "Trace" for full logging.
  // Default is "None".
  "logging": {
    "level": "None"
  },
  "loader": {
    "type": "CommonJS",
    "manualLoading": false
  }
}

```

I read this thread https://forums.bridge.net/forum/community/help/5091-creating-a-node-js-module-with-bridge-net but not understand how to use it with webpack
Also i tried write index.js with this code 
````
require('./bridge');
require('./bridge.meta')
require('./newtonsoft.json.js')
const Demo= require('./Demo.js');
console.log(Demo)
````
And got error 
```
D:\Repositories\data-mapper\demo.js:9
    define("Demo", function () {
    ^

ReferenceError: define is not defined
    at D:\Repositories\data-mapper\demo.js:9:5
    at Object.Bridge.assembly (D:\Repositories\data-mapper\bridge.js:3358:22)
    at Object.<anonymous> (D:\Repositories\data-mapper\demo.js:6:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
PS D:\Repositories\data-mapper>
```

Can you give example how to use your code with webpack and other bundlers?
I dont understand how to use my generated code

**Comment by fabriciomurta** [comment]
Hello! We have a thread about this in our forums under [How does Bridge.NET fit in with module bundlers?](https://forums.bridge.net/forum/general/open-discussions/3079).

I don't know an example using WebPack we may have. We have some demos under [bridgedotnet/Demos](https://github.com/bridgedotnet/Demos/) repository, but I don't think we have any highlighting WebPack, unfortunately.

We added the 'help wanted' tag here in hopes somebody from the community would step in to draw a guide or example on using WebPack with Bridge. According to the thread above, that might be quite possible.
