### ISSUE TITLE
Linq methods not compiled on Enumerable when involving ValueTuples

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#3754]
This is an extension of issue #3728 which fixed the issue for Linq `First()` only. It was initially reported by @hardhub.

Unfortunately the fix provided by the issue above didn't fix for other Linq calls, like `Select()`. More tests should be written now.

### Steps To Reproduce

This is the same initial test case as issue #3728, just changing the `First()` call into `Select`:
https://deck.net/e055938757de981353c14b626b915bda

This deck is based on the existing unit tests, expanding to the Select() call. More should be added:
https://deck.net/ccb74441513e59dae6dc5a51aa50d26b

### Expected Result

It would build and result in valid code with output:

```
Success: Linq.First() works.
Failure: Linq.Select() object-casting works.
Success: Linq.Select() works.
Statistics:
- Passing: 2 (66%)
- Failing: 1 (34%)
- Total: 3
```

### Actual Result

Compiler errors:

```
C# to JavaScript Compilation Failed

System.AggregateException: One or more errors occurred. ---> Bridge.Contract.EmitterException: Error parsing code.
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\p4prv0roj44hjfnnsmugoeum.cs:50,128: Unexpected symbol `A', expecting `.'
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\p4prv0roj44hjfnnsmugoeum.cs:50,147: Unexpected symbol `>', expecting `.'
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\p4prv0roj44hjfnnsmugoeum.cs:50,177: Unexpected symbol `)', expecting `,', `;', or `}'
   at Bridge.Translator.Translator.BuildSyntaxTreeForFile(Int32 index, String[]& rewriten)
   at Bridge.Translator.Translator.<>c__DisplayClass92_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Bridge.Translator.Translator.BuildSyntaxTree()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
---> (Inner Exception #0) Bridge.Contract.EmitterException: Error parsing code.
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\p4prv0roj44hjfnnsmugoeum.cs:50,128: Unexpected symbol `A', expecting `.'
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\p4prv0roj44hjfnnsmugoeum.cs:50,147: Unexpected symbol `>', expecting `.'
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\p4prv0roj44hjfnnsmugoeum.cs:50,177: Unexpected symbol `)', expecting `,', `;', or `}'
   at Bridge.Translator.Translator.BuildSyntaxTreeForFile(Int32 index, String[]& rewriten)
   at Bridge.Translator.Translator.<>c__DisplayClass92_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by hardhub** [comment]
Hello, Fabrício!
I will review my current project workarounds.  
But of course it is better to get 17.5.0 first.  
So I will be sure it works in real world (not only on deck samples).
Sometimes test samples and real code (with complex types) run differently.

**Comment by fabriciomurta** [comment]
Looks as good as fixed now. Tried several different linq extensions and failed to break the code in all attempts. This batch of fixes is going to make it to the next Bridge release (see milestone).
