### ISSUE TITLE
Generic dictionary cast into IDictionary's Clear() call triggers exception

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#3778]
Casting a dictionary to its interface class and calling at least the `Clear()` method triggers an error at run-time with Bridge.

For instance, the `.Contains("test")` call also triggers an error whereas it works in native .NET.

### Steps To Reproduce

Reported deck: https://dev.deck.net/415d890fdaa845590fed81b10ebf62e9
Deck with Assert wrap-up: https://dev.deck.net/ba1e750162ed483d974e94a281a0cd2d

Reported code sample
```csharp
public class Program
{
    public static void Main()
    {
        Dictionary<string, string> myDict = new Dictionary<string, string>();
        myDict.Add("test", "test");
        IDictionary iDict = myDict as IDictionary;
        iDict.Clear();
    }
}
```

### Expected Result
Based on deck with assertions implemented, dotnet fiddle: https://dotnetfiddle.net/5crhwb

```
Success: Original dictionary has the expected amount of entries.
Success: Interface-cast dictionary has the expected amount of entries.
Success: Interface-cast dictionary Clear() call emptied it.
Statistics:
- Passing: 3 (100%)
- Failing: 0 (0%)
- Total: 3
```

### Actual Result

Based on the [deck above with assertions](https://dev.deck.net/ba1e750162ed483d974e94a281a0cd2d):

```
Success: Original dictionary has the expected amount of entries.
Success: Interface-cast dictionary has the expected amount of entries.
System.Exception: TypeError: iDict.System$Collections$IDictionary$clear is not a function
    at Function.Main (https://dev.deck.net/RunHandler.ashx?h=-229480093:91:19)
    at https://dev.deck.net/resources/js/bridge/bridge.min.js?17.4.0-201810040712:7:42674
    at HTMLDocument.i (https://dev.deck.net/resources/js/bridge/bridge.min.js?17.4.0-201810040712:7:6515)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)
    at n.fn.init.n.fn.ready (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:29515)
    at new n.fn.init (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:24945)
    at n (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:405)
    at Object.ready (https://dev.deck.net/resources/js/bridge/bridge.min.js?17.4.0-201810040712:7:6578)
    at https://dev.deck.net/resources/js/bridge/bridge.min.js?17.4.0-201810040712:7:42647
```

**Comment by vladsch** [comment]
Fixed in https://github.com/bridgedotnet/Bridge/pull/3841

**Comment by fabriciomurta** [comment]
Merged onto `dev` now, it will be available next Bridge release, in accordance with this issue's milestone.
