### ISSUE TITLE
Nullable type arguments fail to compile - OrderByDescending

### ISSUE THREAD

**Issue by FasettoAndrew** [bridgedotnet/Bridge#3785]
When using a nullable type as a type argument for a method, bridge fails to compile.

In this example i'm using the OrderByDescending method with a DateTimeOffset? property.

### Steps To Reproduce

https://deck.net/e9120eb7517df09c149b419ee334ea59

```csharp
public class Program
{
    public static void Main()
    {       
        var a = new List<Model>();
        
        a.OrderByDescending(i => i.CreatedDate);
    }
}

public class Model
{
    public DateTimeOffset? CreatedDate { get; set; }
}
```

### Expected Result

Bridge compiles Javascript correctly.

### Actual Result

```js
C# to JavaScript Compilation Failed

System.AggregateException: One or more errors occurred. ---> Bridge.Contract.EmitterException: Error parsing code.
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\fqfc2fvre3jzjtl1jx5j3crj.cs:30,63: Type expected
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\fqfc2fvre3jzjtl1jx5j3crj.cs:30,77: Unexpected symbol `>'
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\fqfc2fvre3jzjtl1jx5j3crj.cs:31,14: Unexpected symbol `('
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\fqfc2fvre3jzjtl1jx5j3crj.cs:31,40: Unexpected symbol `?'
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\fqfc2fvre3jzjtl1jx5j3crj.cs:31,81: Internal compiler error during parsingSystem.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Pop()
   at ICSharpCode.NRefactory.MonoCSharp.CSharpParser.PopLocation()
   at ICSharpCode.NRefactory.MonoCSharp.CSharpParser.case_874()
   at ICSharpCode.NRefactory.MonoCSharp.CSharpParser.yyparse(yyInput yyLex)
   at ICSharpCode.NRefactory.MonoCSharp.CSharpParser.parse()
   at Bridge.Translator.Translator.BuildSyntaxTreeForFile(Int32 index, String[]& rewriten)
   at Bridge.Translator.Translator.<>c__DisplayClass92_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Bridge.Translator.Translator.BuildSyntaxTree()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
---> (Inner Exception #0) Bridge.Contract.EmitterException: Error parsing code.
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\fqfc2fvre3jzjtl1jx5j3crj.cs:30,63: Type expected
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\fqfc2fvre3jzjtl1jx5j3crj.cs:30,77: Unexpected symbol `>'
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\fqfc2fvre3jzjtl1jx5j3crj.cs:31,14: Unexpected symbol `('
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\fqfc2fvre3jzjtl1jx5j3crj.cs:31,40: Unexpected symbol `?'
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\fqfc2fvre3jzjtl1jx5j3crj.cs:31,81: Internal compiler error during parsingSystem.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Pop()
   at ICSharpCode.NRefactory.MonoCSharp.CSharpParser.PopLocation()
   at ICSharpCode.NRefactory.MonoCSharp.CSharpParser.case_874()
   at ICSharpCode.NRefactory.MonoCSharp.CSharpParser.yyparse(yyInput yyLex)
   at ICSharpCode.NRefactory.MonoCSharp.CSharpParser.parse()
   at Bridge.Translator.Translator.BuildSyntaxTreeForFile(Int32 index, String[]& rewriten)
   at Bridge.Translator.Translator.<>c__DisplayClass92_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

### Additional note

Using the exact same code with a non-nullable type works correct. Here is the above example using a DateTimeOffset rather than a DateTimeOffset?:

https://deck.net/8528093f887427e07d0515589ae865f5

**Comment by fabriciomurta** [comment]
Yes, the code should work just fine with Bridge.
Here's the test cases "assertion-friendly" on Deck and dotnet fiddle:

- https://dotnetfiddle.net/xIna81
- https://deck.net/4d44ea77b91d40630679e4833d6e4470

**Comment by tytusse** [comment]
Also this seems related: https://deck.net/1567be857b0fc2dbd86ad1c8f49957ab

**Comment by fabriciomurta** [comment]
Fixed! The fix will make it to the next release (see attached milestone).
The deck pointed by @tytusse seems to work fine now, too.
