### ISSUE TITLE
Strange compile time regression in 17.5.0

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3790]
https://deck.net/43266758b13eb89298de2f80535ba711

```C#
using System;

public class Program
{
	public static void Main(string[] args)
	{
		MyClass mc = new MyClass();

		Console.WriteLine(mc.GetType().Name);
	}
}

public class MyClass
{
	public MyClass()
	{
		this.Test(null);
	}

	private void Test(Action<TimeSpan?> callback)
	{
	}
}
```

### Actual Result

```
C# to JavaScript Compilation Failed

System.AggregateException: One or more errors occurred. ---> Bridge.Contract.EmitterException: Error parsing code.
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\kabo15e3blvvcs31jxs3cufe.cs:17,30: Type expected
   at Bridge.Translator.Translator.BuildSyntaxTreeForFile(Int32 index, String[]& rewriten)
   at Bridge.Translator.Translator.<>c__DisplayClass92_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Bridge.Translator.Translator.BuildSyntaxTree()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
---> (Inner Exception #0) Bridge.Contract.EmitterException: Error parsing code.
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\kabo15e3blvvcs31jxs3cufe.cs:17,30: Type expected
   at Bridge.Translator.Translator.BuildSyntaxTreeForFile(Int32 index, String[]& rewriten)
   at Bridge.Translator.Translator.<>c__DisplayClass92_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

```

**Comment by fabriciomurta** [comment]
Fixed! The fix will be included in the next version!
