### ISSUE TITLE
JavaScript compilation failed when use long.MinValue in constant property. (Bridge 17.6.0)

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge#3811]
A description of the issue.

### Steps To Reproduce

https://deck.net/3bbe43f25f86693bf6c9ed66c6d7d6b6

I think, the problem is that i use `const`, because if i replace `Settings.DefaultMinValue` to `long.MinValue` - everything is fine.
If i try to use in `const` field `long.MaxValue` - everything is fine.

```csharp
public class MainClass
{
    public long Long1
    {
        get { return minValue; }
        set
        {
            minValue = value < minValue ? Settings.DefaultMinValue : value;
        }      // Error in this line
    }

    private long minValue;
}

public class Settings
{
    public const long DefaultMinValue = long.MinValue;
}
```

### Actual Result

```
C# to JavaScript Compilation Failed
  System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.NRefactory.CSharp.Resolver.CSharpConversions.ImplicitConstantExpressionConversion(ResolveResult rr, IType toType)
   at ICSharpCode.NRefactory.CSharp.Resolver.CSharpConversions.ImplicitConversion(ResolveResult resolveResult, IType toType, Boolean allowUserDefined)
   at ICSharpCode.NRefactory.CSharp.Resolver.CSharpConversions.ImplicitConversion(ResolveResult resolveResult, IType toType)
   at ICSharpCode.NRefactory.CSharp.Resolver.CSharpResolver.ResolveConditional(ResolveResult condition, ResolveResult trueExpression, ResolveResult falseExpression)
   at ICSharpCode.NRefactory.CSharp.Resolver.ResolveVisitor.ICSharpCode.NRefactory.CSharp.IAstVisitor<ICSharpCode.NRefactory.Semantics.ResolveResult>.VisitConditionalExpression(ConditionalExpression conditionalExpression)
   at ICSharpCode.NRefactory.CSharp.ConditionalExpression.AcceptVisitor[T](IAstVisitor`1 visitor)
   at ICSharpCode.NRefactory.CSharp.Resolver.ResolveVisitor.Resolve(AstNode node)
   at ICSharpCode.NRefactory.CSharp.Resolver.ResolveVisitor.Scan(AstNode node)
   at ICSharpCode.NRefactory.CSharp.Resolver.ResolveVisitor.<>c__DisplayClass34_0.<GetResolveResult>b__0()
   at ICSharpCode.NRefactory.CSharp.Resolver.ResolveVisitor.ResetContext(CSharpResolver storedContext, Action action)
   at ICSharpCode.NRefactory.CSharp.Resolver.ResolveVisitor.GetResolveResult(AstNode node)
   at ICSharpCode.NRefactory.CSharp.Resolver.CSharpAstResolver.Resolve(AstNode node, CancellationToken cancellationToken)
   at Bridge.Translator.MemberResolver.ResolveNode(AstNode node, ILog log)
```

**Comment by fabriciomurta** [comment]
Fixed! The fix will be available next Bridge release! See attached milestone for the version it will fall into.
