### ISSUE TITLE
Exception in emitter when F(out var x) used with a generic using alias

### ISSUE THREAD

**Issue by shonk-msft** [bridgedotnet/Bridge#4072]
An exception is thrown in the emitter when an "out var x" arg is provided and the type is a generic using alias. The call stack is below. Note that there is also a warning.

### Steps To Reproduce

Code something like:

https://deck.net/40425476dbe6d4f7754e27de22b19f0e

```csharp
using Wrapper = System.Collections.Generic.List<int>;

public static class C
{
    /// <summary>
    /// This demonstrates issue 4072.
    /// </summary>
    public static Wrapper Get()
    {
#if true // Change to false for workaround.
        bool c = TryGet(out Wrapper x);
#else
        Wrapper x;
        bool c = TryGet(out x);
#endif
        return x;
    }

    private static bool TryGet(out Wrapper x)
    {
        x = new Wrapper();
        return true;
    }
}
```

### Expected Result

Translation to succeed.

### Actual Result

Exception in Bridge.Translator.Emitter.GetTypeDefinition, warning and call stack:

```
1>packages\Bridge.Min.17.9.0\build\Bridge.Min.targets(25,5): warning : 2019-10-17T12:42:09:710 	Warning		Node resolving has failed (Line 7, Col 1): Wrapper<int>
1>BridgeBug.cs(8,2,8,17): error : 2019-10-17T12:42:09:711 	Error		Object reference not set to an instance of an object.    at Bridge.Translator.Emitter.GetTypeDefinition(AstType reference, Boolean safe)
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.VariableBlock.VisitVariableDeclarationStatement()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.VariableBlock.DoEmit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.Emitter.VisitVariableDeclarationStatement(VariableDeclarationStatement variableDeclarationStatement)
1>BridgeBug.cs(8,2,8,17): error :    at ICSharpCode.NRefactory.CSharp.VariableDeclarationStatement.AcceptVisitor(IAstVisitor visitor)
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.Block.<>c__DisplayClass55_0.<DoEmitBlock>b__0(AstNode child)
1>BridgeBug.cs(8,2,8,17): error :    at System.Collections.Generic.List`1.ForEach(Action`1 action)
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.Block.DoEmitBlock()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.Block.EmitBlock()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.Block.DoEmit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
1>BridgeBug.cs(8,2,8,17): error :    at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.VisitorMethodBlock.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.VisitorMethodBlock.DoEmit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.Emitter.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.MethodBlock.EmitMethodsGroup(List`1 group)
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.MethodBlock.EmitMethods(Dictionary`2 methods, Dictionary`2 properties, Dictionary`2 operators)
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.MethodBlock.DoEmit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.ClassBlock.EmitStaticBlock()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.ClassBlock.DoEmit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.EmitBlock.DoEmit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.AbstractEmitterBlock.Emit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.Emitter.Emit()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Translator.Translator.Translate()
1>BridgeBug.cs(8,2,8,17): error :    at Bridge.Build.BridgeCompilerTask.Execute()
```

**Comment by shonk-msft** [comment]
Note that changing the Get method to say:
```csharp
Wrapper x;
bool c = TryGet(out x);
```
avoids the exception and warning.

**Comment by geoffreymcgill** [comment]
Hi @shonk-msft. Thanks for letting us know about this issue. 

Any chance you could share a [Deck.NET](https://deck.net) sample demonstrating how to reproduce?

**Comment by geoffreymcgill** [comment]
I made a sample in Deck.

https://deck.net/802b473142e5838ed5c7b0f9bfdb3039

```csharp
using System;
using Bridge;
using Wrapper = System.Collections.Generic.List<int>;
        
namespace demo
{  
    public static class C
    {
        public static Wrapper Get()
        {
            bool c = TryGet(out var x);
            return x;
        }

        private static bool TryGet(out Wrapper x)
        {
            x = new Wrapper();
            
            return true;
        }
    }   
}
```

**Comment by shonk-msft** [comment]
Yep, that’s it. Here’s a slight tweak, that let’s you easily switch between the crash and workaround:

using Wrapper = System.Collections.Generic.List<int>;

public static class C
{
    /// <summary>
    /// This demonstrates issue 4072: https://github.com/bridgedotnet/Bridge/issues/4072.
    /// </summary>
    public static Wrapper Get()
    {
#if false // Changing to true demonstrates the bug.
        bool c = TryGet(out Wrapper x);
#else
        Wrapper x;
        bool c = TryGet(out x);
#endif
        return x;
    }

    private static bool TryGet(out Wrapper x)
    {
        x = new Wrapper();
        return true;
    }
}

**Comment by shonk-msft** [comment]
Here's one that demonstrates a work around:

https://deck.net/40425476dbe6d4f7754e27de22b19f0e

**Comment by vladsch** [comment]
Fix https://github.com/bridgedotnet/Bridge/pull/4078

**Comment by geoffreymcgill** [comment]
A fix for this issue has been found. 

https://github.com/bridgedotnet/Bridge/pull/4078/files

Further review and testing is required before the PR is accepted. We are working on those steps now.

**Comment by fabriciomurta** [comment]
The changes look good and should make it to the next Bridge release!

**Comment by geoffreymcgill** [comment]
This issue has been fixed and is available to live test in dev.deck.net. Here's a slightly modified version of the original deck that writes something to the **Console**.

// Fails until 17.10.0 is released
https://deck.net/f91d415d2da3c3dcc4a750668989ce17

// Works
https://dev.deck.net/f91d415d2da3c3dcc4a750668989ce17

```csharp
using Wrapper = System.Collections.Generic.List<int>;

public static class C
{
    static void Main()
    {
        var list = Get();
        list.Add(55);
        
    	System.Console.WriteLine(list);
    }
    
    /// <summary>
    /// This demonstrates issue 4072.
    /// </summary>
    public static Wrapper Get()
    {
        bool c = TryGet(out Wrapper x);
        return x;
    }

    private static bool TryGet(out Wrapper x)
    {
        x = new Wrapper();
        return true;
    }
}
```
