### ISSUE TITLE
Crash when iterator uses goto

### ISSUE THREAD

**Issue by shonk-msft** [bridgedotnet/Bridge#4083]
Bridge.Net crashes with an `ArgumentNullException` when an iterator uses goto.

### Steps To Reproduce

https://deck.net/3705195e768017f1fe2550ed4e55d380

```csharp
    using System.Collections.Generic;
    using System.Diagnostics;

    public class RedBlackNode<V>
    {
        public readonly string Key;
        public readonly V Value;
        public readonly RedBlackNode<V> Left;
        public readonly RedBlackNode<V> Right;

        public static IEnumerable<KeyValuePair<string, V>> GetPairs(RedBlackNode<V> root)
        {
            if (root == null)
                yield break;

            Stack<RedBlackNode<V>> stack = new Stack<RedBlackNode<V>>();
            RedBlackNode<V> node = root;

            // Bridge.Net crashes on the goto version, so rewritten as a state machine.
            // Change to #if false for the state machine version.
#if true
        LStart:
            if (node.Left != null)
            {
                stack.Push(node);
                node = node.Left;
                goto LStart;
            }

        LYieldSelf:
            yield return new KeyValuePair<string, V>(node.Key, node.Value);

            if (node.Right != null)
            {
                node = node.Right;
                goto LStart;
            }

            if (stack.Count == 0)
                yield break;

            node = stack.Pop();
            goto LYieldSelf;
#else
            const int stateLeft = 0;
            const int stateThis = 1;
            const int stateRght = 2;
            const int stateGoUp = 3;

            int state = stateLeft;
            for (; ; )
            {
                switch (state)
                {
                case stateLeft:
                    if (node.Left != null)
                    {
                        stack.Push(node);
                        node = node.Left;
                        Debug.Assert(state == stateLeft);
                    }
                    else
                        state = stateThis;
                    break;

                case stateThis:
                    yield return new KeyValuePair<string, V>(node.Key, node.Value);
                    state = stateRght;
                    break;

                case stateRght:
                    if (node.Right != null)
                    {
                        node = node.Right;
                        state = stateLeft;
                    }
                    else
                        state = stateGoUp;
                    break;

                default:
                    Debug.Assert(state == stateGoUp);
                    if (stack.Count == 0)
                        yield break;
                    node = stack.Pop();
                    state = stateThis;
                    break;
                }
            }
#endif
        }
    }
```

### Expected Result

No crash.

### Actual Result

```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Bridge.Translator.GotoBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitGotoStatement(GotoStatement gotoStatement)
   at ICSharpCode.NRefactory.CSharp.GotoStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.Block.<>c__DisplayClass55_0.<DoEmitBlock>b__0(AstNode child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Bridge.Translator.Block.DoEmitBlock()
   at Bridge.Translator.Block.EmitBlock()
   at Bridge.Translator.Block.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.IfElseBlock.VisitIfElseStatement()
   at Bridge.Translator.IfElseBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitIfElseStatement(IfElseStatement ifElseStatement)
   at ICSharpCode.NRefactory.CSharp.IfElseStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.Block.<>c__DisplayClass55_0.<DoEmitBlock>b__0(AstNode child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Bridge.Translator.Block.DoEmitBlock()
   at Bridge.Translator.Block.EmitBlock()
   at Bridge.Translator.Block.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.GeneratorBlock.EmitGeneratorBody()
   at Bridge.Translator.GeneratorBlock.EmitGeneratorBlock()
   at Bridge.Translator.GeneratorBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.VisitorMethodBlock.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.VisitorMethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.MethodBlock.EmitMethodsGroup(List`1 group)
   at Bridge.Translator.MethodBlock.EmitMethods(Dictionary`2 methods, Dictionary`2 properties, Dictionary`2 operators)
   at Bridge.Translator.MethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.ClassBlock.EmitStaticBlock()
   at Bridge.Translator.ClassBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
```

**Comment by geoffreymcgill** [comment]
Well, this is going to be an interesting one to figure out.

Thanks for the report and excellent sample demonstrating how to reproduce. We'll do our best to try and support this scenario.

**Comment by fabriciomurta** [comment]
Fixed! We are going to include this fix in the next Bridge release.
