### ISSUE TITLE
Parsing problem with #if

### ISSUE THREAD

**Issue by shonk-msft** [bridgedotnet/Bridge#4095]
Parsing throws on the following deck.

### Steps To Reproduce

https://deck.net/7cd79a9f34d0e01d3e9af6618c44de15

```csharp
using System;

public abstract class A
{
    public A Child { get; }

    protected A(A child)
    {
        Child = child;
    }
}

public sealed class B : A
{
    private B(A child)
        : base(child)
    {
#if DEBUG
        Console.WriteLine("A");
#endif
    }

    public static B Create(A child)
    {
#if DEBUG
        Console.WriteLine("B");
#endif

        if (child is B b)
            return new B(b.Child);

        return new B(child);
    }
}
```

When the `if (child is B b) return new B(b.Child);` code is commented out, parsing succeeds.

### Expected Result

Parse successfully.

### Actual Result

```
C# to JavaScript Compilation Failed

System.AggregateException: One or more errors occurred. ---> Bridge.Contract.EmitterException: Error parsing code.
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\bxag05xs35oajiq5o3m0bbgn.cs:27,5: Preprocessor directives must appear as the first non-whitespace character on a line
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\bxag05xs35oajiq5o3m0bbgn.cs:29,8: Unexpected symbol `if'
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\bxag05xs35oajiq5o3m0bbgn.cs:35,1: Expected `#endif' directive
   at Bridge.Translator.Translator.BuildSyntaxTreeForFile(Int32 index, String[]& rewriten)
   at Bridge.Translator.Translator.<>c__DisplayClass93_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Bridge.Translator.Translator.BuildSyntaxTree()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
---> (Inner Exception #0) Bridge.Contract.EmitterException: Error parsing code.
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\bxag05xs35oajiq5o3m0bbgn.cs:27,5: Preprocessor directives must appear as the first non-whitespace character on a line
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\bxag05xs35oajiq5o3m0bbgn.cs:29,8: Unexpected symbol `if'
E:\HostingSpaces\object\deck.net\wwwroot\UserCode\bxag05xs35oajiq5o3m0bbgn.cs:35,1: Expected `#endif' directive
   at Bridge.Translator.Translator.BuildSyntaxTreeForFile(Int32 index, String[]& rewriten)
   at Bridge.Translator.Translator.<>c__DisplayClass93_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by geoffreymcgill** [comment]
@shonk-msft – Thanks for the report. Looks like this should be an easy fix. We will investigate and try to fix right away.
