### ISSUE TITLE
Only 3 foreach() statements allowed in a method

### ISSUE THREAD

**Issue by gogglespisano** [bridgedotnet/Bridge#502]
If you have 4 or more foreach() statements in an method, the compiler has an error saying a dictionary key already exists.

Error: An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Bridge.Translator.AbstractEmitterBlock.AddLocal(String name, AstType type)
   at Bridge.Translator.ForeachBlock.VisitForeachStatement(Nullable`1 replaceAwaiterByVar)
   at Bridge.Translator.ForeachBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitForeachStatement(ForeachStatement foreachStatement)
   at ICSharpCode.NRefactory.CSharp.ForeachStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Contract.Helpers.AcceptChildren(AstNode node, IAstVisitor visitor)
   at Bridge.Translator.ConstructorBlock.EmitCtorForInstantiableClass()
   at Bridge.Translator.ConstructorBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.ClassBlock.EmitInstantiableBlock()
   at Bridge.Translator.ClassBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.GenerateScript.Execute()

public class App
{
    [Ready]
    public static void Main()
    {
        int[] numbers = {1,2,3};

        foreach(int a in numbers)
        {
        }

        foreach(int a in numbers)
        {
        }

        foreach(int a in numbers)
        {
        }

        foreach(int a in numbers)
        {
        }
    }
}

fails on the live editor because it reuses variable "a1"

/* global Bridge */

Bridge.define('LiveApp.App', {
    statics: {
        config: {
            init: function () {
                Bridge.ready(this.main);
            }
        },
        main: function () {
            var $t, $t1, $t2, $t3;
            var numbers = [1, 2, 3];

            $t = Bridge.getEnumerator(numbers);
            while ($t.moveNext()) {
                var a = $t.getCurrent();
            }

            $t1 = Bridge.getEnumerator(numbers);
            while ($t1.moveNext()) {
                var a1 = $t1.getCurrent();
            }

            $t2 = Bridge.getEnumerator(numbers);
            while ($t2.moveNext()) {
                var a11 = $t2.getCurrent();
            }

            $t3 = Bridge.getEnumerator(numbers);
            while ($t3.moveNext()) {
                var a1 = $t3.getCurrent();
            }
        }
    }
});

**Comment by vladsch** [comment]
I cannot reproduce compiler exception with latest code. The issue with variable names is fixed

**Comment by LeonidVeriga** [comment]
Hi @gogglespisano. Thank you for reporting this issue!

The same result for me against the latest `release1.10` branch - not reproducible now. We have added a unit test to check this issue will not appear anymore.

**Comment by gogglespisano** [comment]
Thanks.
