### ISSUE TITLE
Casting object as Func<object> causes "Delegate's methods are not supported. Please use direct delegate invoke"

### ISSUE THREAD

**Issue by maverix** [bridgedotnet/Bridge#654]
Hi,

I am evaluating using Bridge.net for migrating from a large Script# project.  
Really liking it so far.  One small snag I have hit is when I have a object which could be a function or an object, a common scenario in a dynamic language like JavaScript

            Func<object> func = item as Func<object>;

            if (!func.IsNullOrUndefined())
                item = func.Invoke();

            return item;

The above code gives an error when compiling: Error: Delegate's methods are not supported. Please use direct delegate invoke.

I have tried func(); which also causes the same error.

Am I missing something?

**Comment by maverix** [comment]
Full Error Message below:

Error	2	Error: Delegate's methods are not supported. Please use direct delegate invoke.    at Bridge.Translator.InvocationBlock.VisitInvocationExpression()
   at Bridge.Translator.InvocationBlock.EmitConversionExpression()
   at Bridge.Translator.ConversionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitInvocationExpression(InvocationExpression invocationExpression)
   at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.UnaryOperatorBlock.VisitUnaryOperatorExpression()
   at Bridge.Translator.UnaryOperatorBlock.EmitConversionExpression()
   at Bridge.Translator.ConversionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitUnaryOperatorExpression(UnaryOperatorExpression unaryOperatorExpression)
   at ICSharpCode.NRefactory.CSharp.UnaryOperatorExpression.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.IfElseBlock.VisitIfElseStatement()
   at Bridge.Translator.IfElseBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitIfElseStatement(IfElseStatement ifElseStatement)
   at ICSharpCode.NRefactory.CSharp.IfElseStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.Block.<DoEmitBlock>b__1(AstNode child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Bridge.Translator.Block.DoEmitBlock()
   at Bridge.Translator.Block.EmitBlock()
   at Bridge.Translator.Block.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitBlockStatement(BlockStatement blockStatement)
   at ICSharpCode.NRefactory.CSharp.BlockStatement.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Translator.VisitorMethodBlock.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.VisitorMethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.MethodBlock.EmitMethodsGroup(List`1 group)
   at Bridge.Translator.MethodBlock.EmitMethods(Dictionary`2 methods, Dictionary`2 properties, Dictionary`2 operators)
   at Bridge.Translator.MethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.ClassBlock.EmitStaticBlock()
   at Bridge.Translator.ClassBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.GenerateScript.Execute()	E:\Projects\SLC\SLC.Bridge\Application.cs	143	19	SLC.Bridge

**Comment by geoffreymcgill** [comment]
HI @maverix,

Thanks for the report. We are investigating and will get back to you shortly with an answer. 

I'd be interested in hearing about your Script#-to-Bridge.NET upgrade experience.

**Comment by vladsch** [comment]
Yes, Invoke for delegates is not supported now but you can invoke delegates directly
See http://live.bridge.net/#4d3ae3e25aed45386856

Can you provide full test case where you tried func()?

**Comment by maverix** [comment]
Thanks for the prompt responses!  Really appreciate it.

Turns out this was a bit of a red herring.  I have the working code now in http://live.bridge.net/#9c55d90ee154ecd5845a

The part I was doing wrong was using an extension method on object on a Func

The offending extension method below

    static class ObjectExtensions {

        internal static bool IsNullOrUndefined(this object subject) {
            return subject == Script.Undefined || subject == null;
        }

    }

**Comment by maverix** [comment]
Would be nice if that extension method worked on a function of course

**Comment by vladsch** [comment]
Yes, extension methods should work for delegates, we will fix it

**Comment by vladsch** [comment]
I opened the issue
https://github.com/bridgedotnet/Bridge/issues/655

**Comment by LeonidVeriga** [comment]
@maverix, we will include #655 into `1.10.2` so extention methods can be used for delegates.
