### ISSUE TITLE
Nested class may be generated before its parent class

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#73]
A sporadic issue, as a result - nested class gets overriden by its parent class code (i.e. removed).

In `js` it looks like:
```
TypeError: undefined is not a function
    at Class.Bridge.Class.define.constructor [as $constructor] (http://localhost:20000/Tests/TestSets.js:220:35)
    at Class.Bridge.Class.initCtor [as $$initCtor] (http://localhost:20000/Tests/bridge.js:842:29)
    at new Class (http://localhost:20000/Tests/bridge.js:972:33)
```

A workaround is to use `[SerializationPriority(-1)]` for the nested class to force it be serialized after the parent class (with `SerializationPriority = 0` by default).

**Comment by vladsch** [comment]
I guess it can be closed already
