### ISSUE TITLE
Compiler crash due to unsigned enum

### ISSUE THREAD

**Issue by strygo** [bridgedotnet/Bridge#857]
While converting an existing .NET library to Bridge, I hit a compiler error caused by the following code:

```
    public enum TestEnum : uint
    {
        All = 0xFFFFFFFF,
    }
```

This results in the following compiler crash:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Error: Specified cast is not valid.    at Bridge.Translator.Inspector.VisitEnumMemberDeclaration(EnumMemberDeclaration enumMemberDeclaration)
   at ICSharpCode.NRefactory.CSharp.EnumMemberDeclaration.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Contract.Helpers.AcceptChildren(AstNode node, IAstVisitor visitor)
   at Bridge.Translator.Inspector.VisitTypeDeclaration(TypeDeclaration typeDeclaration)
   at ICSharpCode.NRefactory.CSharp.TypeDeclaration.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Contract.Helpers.AcceptChildren(AstNode node, IAstVisitor visitor)
   at Bridge.Translator.Inspector.VisitNamespaceDeclaration(NamespaceDeclaration namespaceDeclaration)
   at ICSharpCode.NRefactory.CSharp.NamespaceDeclaration.AcceptVisitor(IAstVisitor visitor)
   at Bridge.Contract.Helpers.AcceptChildren(AstNode node, IAstVisitor visitor)
   at Bridge.Translator.Inspector.VisitSyntaxTree(SyntaxTree node)
   at Bridge.Translator.Translator.InspectTypes(MemberResolver resolver, IAssemblyInfo config)
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.GenerateScript.Execute()	ClassLibrary2			
```

**Comment by LeonidVeriga** [comment]
@strygo,

Thank you for reporting this issue.

**Comment by strygo** [comment]
No problem. Thanks for the quick fix!
